// Code generated by goderive DO NOT EDIT.

package model

import (
	"database/sql"
	"sync"
	"time"

	"etop.vn/backend/pkg/common/cmsql"
	core "etop.vn/backend/pkg/common/sq/core"
)

var __sqlModels []interface{ SQLVerifySchema(db *cmsql.Database) }
var __sqlonce sync.Once

func SQLVerifySchema(db *cmsql.Database) {
	__sqlonce.Do(func() {
		for _, m := range __sqlModels {
			m.SQLVerifySchema(db)
		}
	})
}

type SQLWriter = core.SQLWriter

// Type Receipt represents table receipt
func sqlgenReceipt(_ *Receipt) bool { return true }

type Receipts []*Receipt

const __sqlReceipt_Table = "receipt"
const __sqlReceipt_ListCols = "\"id\",\"shop_id\",\"trader_id\",\"code\",\"title\",\"type\",\"description\",\"amount\",\"status\",\"order_ids\",\"lines\",\"created_by\",\"created_at\",\"updated_at\",\"deleted_at\""
const __sqlReceipt_Insert = "INSERT INTO \"receipt\" (" + __sqlReceipt_ListCols + ") VALUES"
const __sqlReceipt_Select = "SELECT " + __sqlReceipt_ListCols + " FROM \"receipt\""
const __sqlReceipt_Select_history = "SELECT " + __sqlReceipt_ListCols + " FROM history.\"receipt\""
const __sqlReceipt_UpdateAll = "UPDATE \"receipt\" SET (" + __sqlReceipt_ListCols + ")"

func (m *Receipt) SQLTableName() string  { return "receipt" }
func (m *Receipts) SQLTableName() string { return "receipt" }
func (m *Receipt) SQLListCols() string   { return __sqlReceipt_ListCols }

func (m *Receipt) SQLVerifySchema(db *cmsql.Database) {
	query := "SELECT " + __sqlReceipt_ListCols + " FROM receipt WHERE false"
	if _, err := db.SQL(query).Exec(); err != nil {
		db.RecordError(err)
	}
}

func init() {
	__sqlModels = append(__sqlModels, (*Receipt)(nil))
}

func (m *Receipt) SQLArgs(opts core.Opts, create bool) []interface{} {
	now := time.Now()
	return []interface{}{
		core.Int64(m.ID),
		core.Int64(m.ShopID),
		core.Int64(m.TraderID),
		core.String(m.Code),
		core.String(m.Title),
		core.String(m.Type),
		core.String(m.Description),
		core.Int32(m.Amount),
		core.Int32(m.Status),
		core.Array{m.OrderIDs, opts},
		core.JSON{m.Lines},
		core.Int64(m.CreatedBy),
		core.Now(m.CreatedAt, now, create),
		core.Now(m.UpdatedAt, now, true),
		core.Time(m.DeletedAt),
	}
}

func (m *Receipt) SQLScanArgs(opts core.Opts) []interface{} {
	return []interface{}{
		(*core.Int64)(&m.ID),
		(*core.Int64)(&m.ShopID),
		(*core.Int64)(&m.TraderID),
		(*core.String)(&m.Code),
		(*core.String)(&m.Title),
		(*core.String)(&m.Type),
		(*core.String)(&m.Description),
		(*core.Int32)(&m.Amount),
		(*core.Int32)(&m.Status),
		core.Array{&m.OrderIDs, opts},
		core.JSON{&m.Lines},
		(*core.Int64)(&m.CreatedBy),
		(*core.Time)(&m.CreatedAt),
		(*core.Time)(&m.UpdatedAt),
		(*core.Time)(&m.DeletedAt),
	}
}

func (m *Receipt) SQLScan(opts core.Opts, row *sql.Row) error {
	return row.Scan(m.SQLScanArgs(opts)...)
}

func (ms *Receipts) SQLScan(opts core.Opts, rows *sql.Rows) error {
	res := make(Receipts, 0, 128)
	for rows.Next() {
		m := new(Receipt)
		args := m.SQLScanArgs(opts)
		if err := rows.Scan(args...); err != nil {
			return err
		}
		res = append(res, m)
	}
	if err := rows.Err(); err != nil {
		return err
	}
	*ms = res
	return nil
}

func (_ *Receipt) SQLSelect(w SQLWriter) error {
	w.WriteQueryString(__sqlReceipt_Select)
	return nil
}

func (_ *Receipts) SQLSelect(w SQLWriter) error {
	w.WriteQueryString(__sqlReceipt_Select)
	return nil
}

func (m *Receipt) SQLInsert(w SQLWriter) error {
	w.WriteQueryString(__sqlReceipt_Insert)
	w.WriteRawString(" (")
	w.WriteMarkers(15)
	w.WriteByte(')')
	w.WriteArgs(m.SQLArgs(w.Opts(), true))
	return nil
}

func (ms Receipts) SQLInsert(w SQLWriter) error {
	w.WriteQueryString(__sqlReceipt_Insert)
	w.WriteRawString(" (")
	for i := 0; i < len(ms); i++ {
		w.WriteMarkers(15)
		w.WriteArgs(ms[i].SQLArgs(w.Opts(), true))
		w.WriteRawString("),(")
	}
	w.TrimLast(2)
	return nil
}

func (m *Receipt) SQLUpdate(w SQLWriter) error {
	now, opts := time.Now(), w.Opts()
	_, _ = now, opts // suppress unuse error
	var flag bool
	w.WriteRawString("UPDATE ")
	w.WriteName("receipt")
	w.WriteRawString(" SET ")
	if m.ID != 0 {
		flag = true
		w.WriteName("id")
		w.WriteByte('=')
		w.WriteMarker()
		w.WriteByte(',')
		w.WriteArg(m.ID)
	}
	if m.ShopID != 0 {
		flag = true
		w.WriteName("shop_id")
		w.WriteByte('=')
		w.WriteMarker()
		w.WriteByte(',')
		w.WriteArg(m.ShopID)
	}
	if m.TraderID != 0 {
		flag = true
		w.WriteName("trader_id")
		w.WriteByte('=')
		w.WriteMarker()
		w.WriteByte(',')
		w.WriteArg(m.TraderID)
	}
	if m.Code != "" {
		flag = true
		w.WriteName("code")
		w.WriteByte('=')
		w.WriteMarker()
		w.WriteByte(',')
		w.WriteArg(m.Code)
	}
	if m.Title != "" {
		flag = true
		w.WriteName("title")
		w.WriteByte('=')
		w.WriteMarker()
		w.WriteByte(',')
		w.WriteArg(m.Title)
	}
	if m.Type != "" {
		flag = true
		w.WriteName("type")
		w.WriteByte('=')
		w.WriteMarker()
		w.WriteByte(',')
		w.WriteArg(m.Type)
	}
	if m.Description != "" {
		flag = true
		w.WriteName("description")
		w.WriteByte('=')
		w.WriteMarker()
		w.WriteByte(',')
		w.WriteArg(m.Description)
	}
	if m.Amount != 0 {
		flag = true
		w.WriteName("amount")
		w.WriteByte('=')
		w.WriteMarker()
		w.WriteByte(',')
		w.WriteArg(m.Amount)
	}
	if m.Status != 0 {
		flag = true
		w.WriteName("status")
		w.WriteByte('=')
		w.WriteMarker()
		w.WriteByte(',')
		w.WriteArg(m.Status)
	}
	if m.OrderIDs != nil {
		flag = true
		w.WriteName("order_ids")
		w.WriteByte('=')
		w.WriteMarker()
		w.WriteByte(',')
		w.WriteArg(core.Array{m.OrderIDs, opts})
	}
	if m.Lines != nil {
		flag = true
		w.WriteName("lines")
		w.WriteByte('=')
		w.WriteMarker()
		w.WriteByte(',')
		w.WriteArg(core.JSON{m.Lines})
	}
	if m.CreatedBy != 0 {
		flag = true
		w.WriteName("created_by")
		w.WriteByte('=')
		w.WriteMarker()
		w.WriteByte(',')
		w.WriteArg(m.CreatedBy)
	}
	if !m.CreatedAt.IsZero() {
		flag = true
		w.WriteName("created_at")
		w.WriteByte('=')
		w.WriteMarker()
		w.WriteByte(',')
		w.WriteArg(m.CreatedAt)
	}
	if !m.UpdatedAt.IsZero() {
		flag = true
		w.WriteName("updated_at")
		w.WriteByte('=')
		w.WriteMarker()
		w.WriteByte(',')
		w.WriteArg(core.Now(m.UpdatedAt, time.Now(), true))
	}
	if !m.DeletedAt.IsZero() {
		flag = true
		w.WriteName("deleted_at")
		w.WriteByte('=')
		w.WriteMarker()
		w.WriteByte(',')
		w.WriteArg(m.DeletedAt)
	}
	if !flag {
		return core.ErrNoColumn
	}
	w.TrimLast(1)
	return nil
}

func (m *Receipt) SQLUpdateAll(w SQLWriter) error {
	w.WriteQueryString(__sqlReceipt_UpdateAll)
	w.WriteRawString(" = (")
	w.WriteMarkers(15)
	w.WriteByte(')')
	w.WriteArgs(m.SQLArgs(w.Opts(), false))
	return nil
}

type ReceiptHistory map[string]interface{}
type ReceiptHistories []map[string]interface{}

func (m *ReceiptHistory) SQLTableName() string  { return "history.\"receipt\"" }
func (m ReceiptHistories) SQLTableName() string { return "history.\"receipt\"" }

func (m *ReceiptHistory) SQLSelect(w SQLWriter) error {
	w.WriteQueryString(__sqlReceipt_Select_history)
	return nil
}

func (m ReceiptHistories) SQLSelect(w SQLWriter) error {
	w.WriteQueryString(__sqlReceipt_Select_history)
	return nil
}

func (m ReceiptHistory) ID() core.Interface          { return core.Interface{m["id"]} }
func (m ReceiptHistory) ShopID() core.Interface      { return core.Interface{m["shop_id"]} }
func (m ReceiptHistory) TraderID() core.Interface    { return core.Interface{m["trader_id"]} }
func (m ReceiptHistory) Code() core.Interface        { return core.Interface{m["code"]} }
func (m ReceiptHistory) Title() core.Interface       { return core.Interface{m["title"]} }
func (m ReceiptHistory) Type() core.Interface        { return core.Interface{m["type"]} }
func (m ReceiptHistory) Description() core.Interface { return core.Interface{m["description"]} }
func (m ReceiptHistory) Amount() core.Interface      { return core.Interface{m["amount"]} }
func (m ReceiptHistory) Status() core.Interface      { return core.Interface{m["status"]} }
func (m ReceiptHistory) OrderIDs() core.Interface    { return core.Interface{m["order_ids"]} }
func (m ReceiptHistory) Lines() core.Interface       { return core.Interface{m["lines"]} }
func (m ReceiptHistory) CreatedBy() core.Interface   { return core.Interface{m["created_by"]} }
func (m ReceiptHistory) CreatedAt() core.Interface   { return core.Interface{m["created_at"]} }
func (m ReceiptHistory) UpdatedAt() core.Interface   { return core.Interface{m["updated_at"]} }
func (m ReceiptHistory) DeletedAt() core.Interface   { return core.Interface{m["deleted_at"]} }

func (m *ReceiptHistory) SQLScan(opts core.Opts, row *sql.Row) error {
	data := make([]interface{}, 15)
	args := make([]interface{}, 15)
	for i := 0; i < 15; i++ {
		args[i] = &data[i]
	}
	if err := row.Scan(args...); err != nil {
		return err
	}
	res := make(ReceiptHistory, 15)
	res["id"] = data[0]
	res["shop_id"] = data[1]
	res["trader_id"] = data[2]
	res["code"] = data[3]
	res["title"] = data[4]
	res["type"] = data[5]
	res["description"] = data[6]
	res["amount"] = data[7]
	res["status"] = data[8]
	res["order_ids"] = data[9]
	res["lines"] = data[10]
	res["created_by"] = data[11]
	res["created_at"] = data[12]
	res["updated_at"] = data[13]
	res["deleted_at"] = data[14]
	*m = res
	return nil
}

func (ms *ReceiptHistories) SQLScan(opts core.Opts, rows *sql.Rows) error {
	data := make([]interface{}, 15)
	args := make([]interface{}, 15)
	for i := 0; i < 15; i++ {
		args[i] = &data[i]
	}
	res := make(ReceiptHistories, 0, 128)
	for rows.Next() {
		if err := rows.Scan(args...); err != nil {
			return err
		}
		m := make(ReceiptHistory)
		m["id"] = data[0]
		m["shop_id"] = data[1]
		m["trader_id"] = data[2]
		m["code"] = data[3]
		m["title"] = data[4]
		m["type"] = data[5]
		m["description"] = data[6]
		m["amount"] = data[7]
		m["status"] = data[8]
		m["order_ids"] = data[9]
		m["lines"] = data[10]
		m["created_by"] = data[11]
		m["created_at"] = data[12]
		m["updated_at"] = data[13]
		m["deleted_at"] = data[14]
		res = append(res, m)
	}
	if err := rows.Err(); err != nil {
		return err
	}
	*ms = res
	return nil
}

// Type ReceiptLine represents table receipt_line
func sqlgenReceiptLine(_ *ReceiptLine) bool { return true }

type ReceiptLines []*ReceiptLine

const __sqlReceiptLine_Table = "receipt_line"
const __sqlReceiptLine_ListCols = "\"order_id\",\"title\",\"amount\""
const __sqlReceiptLine_Insert = "INSERT INTO \"receipt_line\" (" + __sqlReceiptLine_ListCols + ") VALUES"
const __sqlReceiptLine_Select = "SELECT " + __sqlReceiptLine_ListCols + " FROM \"receipt_line\""
const __sqlReceiptLine_Select_history = "SELECT " + __sqlReceiptLine_ListCols + " FROM history.\"receipt_line\""
const __sqlReceiptLine_UpdateAll = "UPDATE \"receipt_line\" SET (" + __sqlReceiptLine_ListCols + ")"

func (m *ReceiptLine) SQLTableName() string  { return "receipt_line" }
func (m *ReceiptLines) SQLTableName() string { return "receipt_line" }
func (m *ReceiptLine) SQLListCols() string   { return __sqlReceiptLine_ListCols }

func (m *ReceiptLine) SQLVerifySchema(db *cmsql.Database) {
	query := "SELECT " + __sqlReceiptLine_ListCols + " FROM receipt_line WHERE false"
	if _, err := db.SQL(query).Exec(); err != nil {
		db.RecordError(err)
	}
}

func init() {
	__sqlModels = append(__sqlModels, (*ReceiptLine)(nil))
}

func (m *ReceiptLine) SQLArgs(opts core.Opts, create bool) []interface{} {
	return []interface{}{
		core.Int64(m.OrderID),
		core.String(m.Title),
		core.Int32(m.Amount),
	}
}

func (m *ReceiptLine) SQLScanArgs(opts core.Opts) []interface{} {
	return []interface{}{
		(*core.Int64)(&m.OrderID),
		(*core.String)(&m.Title),
		(*core.Int32)(&m.Amount),
	}
}

func (m *ReceiptLine) SQLScan(opts core.Opts, row *sql.Row) error {
	return row.Scan(m.SQLScanArgs(opts)...)
}

func (ms *ReceiptLines) SQLScan(opts core.Opts, rows *sql.Rows) error {
	res := make(ReceiptLines, 0, 128)
	for rows.Next() {
		m := new(ReceiptLine)
		args := m.SQLScanArgs(opts)
		if err := rows.Scan(args...); err != nil {
			return err
		}
		res = append(res, m)
	}
	if err := rows.Err(); err != nil {
		return err
	}
	*ms = res
	return nil
}

func (_ *ReceiptLine) SQLSelect(w SQLWriter) error {
	w.WriteQueryString(__sqlReceiptLine_Select)
	return nil
}

func (_ *ReceiptLines) SQLSelect(w SQLWriter) error {
	w.WriteQueryString(__sqlReceiptLine_Select)
	return nil
}

func (m *ReceiptLine) SQLInsert(w SQLWriter) error {
	w.WriteQueryString(__sqlReceiptLine_Insert)
	w.WriteRawString(" (")
	w.WriteMarkers(3)
	w.WriteByte(')')
	w.WriteArgs(m.SQLArgs(w.Opts(), true))
	return nil
}

func (ms ReceiptLines) SQLInsert(w SQLWriter) error {
	w.WriteQueryString(__sqlReceiptLine_Insert)
	w.WriteRawString(" (")
	for i := 0; i < len(ms); i++ {
		w.WriteMarkers(3)
		w.WriteArgs(ms[i].SQLArgs(w.Opts(), true))
		w.WriteRawString("),(")
	}
	w.TrimLast(2)
	return nil
}

func (m *ReceiptLine) SQLUpdate(w SQLWriter) error {
	now, opts := time.Now(), w.Opts()
	_, _ = now, opts // suppress unuse error
	var flag bool
	w.WriteRawString("UPDATE ")
	w.WriteName("receipt_line")
	w.WriteRawString(" SET ")
	if m.OrderID != 0 {
		flag = true
		w.WriteName("order_id")
		w.WriteByte('=')
		w.WriteMarker()
		w.WriteByte(',')
		w.WriteArg(m.OrderID)
	}
	if m.Title != "" {
		flag = true
		w.WriteName("title")
		w.WriteByte('=')
		w.WriteMarker()
		w.WriteByte(',')
		w.WriteArg(m.Title)
	}
	if m.Amount != 0 {
		flag = true
		w.WriteName("amount")
		w.WriteByte('=')
		w.WriteMarker()
		w.WriteByte(',')
		w.WriteArg(m.Amount)
	}
	if !flag {
		return core.ErrNoColumn
	}
	w.TrimLast(1)
	return nil
}

func (m *ReceiptLine) SQLUpdateAll(w SQLWriter) error {
	w.WriteQueryString(__sqlReceiptLine_UpdateAll)
	w.WriteRawString(" = (")
	w.WriteMarkers(3)
	w.WriteByte(')')
	w.WriteArgs(m.SQLArgs(w.Opts(), false))
	return nil
}

type ReceiptLineHistory map[string]interface{}
type ReceiptLineHistories []map[string]interface{}

func (m *ReceiptLineHistory) SQLTableName() string  { return "history.\"receipt_line\"" }
func (m ReceiptLineHistories) SQLTableName() string { return "history.\"receipt_line\"" }

func (m *ReceiptLineHistory) SQLSelect(w SQLWriter) error {
	w.WriteQueryString(__sqlReceiptLine_Select_history)
	return nil
}

func (m ReceiptLineHistories) SQLSelect(w SQLWriter) error {
	w.WriteQueryString(__sqlReceiptLine_Select_history)
	return nil
}

func (m ReceiptLineHistory) OrderID() core.Interface { return core.Interface{m["order_id"]} }
func (m ReceiptLineHistory) Title() core.Interface   { return core.Interface{m["title"]} }
func (m ReceiptLineHistory) Amount() core.Interface  { return core.Interface{m["amount"]} }

func (m *ReceiptLineHistory) SQLScan(opts core.Opts, row *sql.Row) error {
	data := make([]interface{}, 3)
	args := make([]interface{}, 3)
	for i := 0; i < 3; i++ {
		args[i] = &data[i]
	}
	if err := row.Scan(args...); err != nil {
		return err
	}
	res := make(ReceiptLineHistory, 3)
	res["order_id"] = data[0]
	res["title"] = data[1]
	res["amount"] = data[2]
	*m = res
	return nil
}

func (ms *ReceiptLineHistories) SQLScan(opts core.Opts, rows *sql.Rows) error {
	data := make([]interface{}, 3)
	args := make([]interface{}, 3)
	for i := 0; i < 3; i++ {
		args[i] = &data[i]
	}
	res := make(ReceiptLineHistories, 0, 128)
	for rows.Next() {
		if err := rows.Scan(args...); err != nil {
			return err
		}
		m := make(ReceiptLineHistory)
		m["order_id"] = data[0]
		m["title"] = data[1]
		m["amount"] = data[2]
		res = append(res, m)
	}
	if err := rows.Err(); err != nil {
		return err
	}
	*ms = res
	return nil
}
