// +build !generator

// Code generated by generator enum. DO NOT EDIT.

package try_on

import (
	fmt "fmt"

	encode "etop.vn/capi/encode"
)

var __jsonNull = []byte("null")

var enumTryOnCodeName = map[int]string{
	0: "unknown",
	1: "none",
	2: "open",
	3: "try",
}

var enumTryOnCodeValue = map[string]int{
	"unknown": 0,
	"none":    1,
	"open":    2,
	"try":     3,
}

func ParseTryOnCode(s string) (TryOnCode, bool) {
	val, ok := enumTryOnCodeValue[s]
	return TryOnCode(val), ok
}

func (e TryOnCode) Enum() int {
	return int(e)
}

func (e TryOnCode) Wrap() NullTryOnCode {
	return WrapTryOnCode(e)
}

func (e TryOnCode) Name() string {
	return enumTryOnCodeName[e.Enum()]
}

func (e TryOnCode) String() string {
	s, ok := enumTryOnCodeName[e.Enum()]
	if ok {
		return s
	}
	return fmt.Sprintf("TryOnCode(%v)", e.Enum())
}

func (e TryOnCode) MarshalJSON() ([]byte, error) {
	return []byte("\"" + enumTryOnCodeName[e.Enum()] + "\""), nil
}

func (e *TryOnCode) UnmarshalJSON(data []byte) error {
	value, err := encode.UnmarshalJSONEnumInt(enumTryOnCodeValue, data, "TryOnCode")
	if err != nil {
		return err
	}
	*e = TryOnCode(value)
	return nil
}

func (e TryOnCode) Value() (interface{}, error) {
	return e.String(), nil
}

func (e *TryOnCode) Scan(src interface{}) error {
	value, err := encode.ScanEnumInt(enumTryOnCodeValue, src, "TryOnCode")
	*e = (TryOnCode)(value)
	return err
}

type NullTryOnCode struct {
	Enum  TryOnCode
	Valid bool
}

func WrapTryOnCode(enum TryOnCode) NullTryOnCode {
	return NullTryOnCode{Enum: enum, Valid: true}
}

func (n NullTryOnCode) Apply(s TryOnCode) TryOnCode {
	if n.Valid {
		return n.Enum
	}
	return s
}

func (n NullTryOnCode) Value() (interface{}, error) {
	if !n.Valid {
		return nil, nil
	}
	return n.Enum.Value()
}

func (n *NullTryOnCode) Scan(src interface{}) error {
	if src == nil {
		n.Enum, n.Valid = 0, false
		return nil
	}
	n.Valid = true
	return n.Enum.Scan(src)
}

func (n NullTryOnCode) MarshalJSON() ([]byte, error) {
	if n.Valid {
		return n.Enum.MarshalJSON()
	}
	return __jsonNull, nil
}

func (n *NullTryOnCode) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		n.Enum, n.Valid = 0, false
		return nil
	}
	n.Valid = true
	return n.Enum.UnmarshalJSON(data)
}
