stages:
- build
- report

variables:
  ETOPDIR: /etop.vn
  POSTGRES_USER: postgres
  POSTGRES_DB: test
  POSTGRES_PASSWORD: postgres

before_script:
- mkdir -p artifacts
- mkdir -p /etop.vn
- ln -s $PWD /etop.vn/backend

report-gerrit-changes-running:
  stage: build
  tags: [go]
  image: olvrng/alpine-toolbox
  before_script: []
  script:
  - scripts/ci/report-gerrit.sh running

build:
  stage: build
  tags: [go]
  image: olvrng/golang-toolbox
  services:
  - postgres:9.6-alpine
  - redis:alpine
  script:
  - time scripts/ci/cache-load.sh
  - time scripts/verify-imports.sh
  - time scripts/install-tools.sh
  - time go run ./scripts/init_testdb/main.go -drop
  - time scripts/ci/test-all.sh
  - time scripts/ci/cache-save.sh
  - touch artifacts/BUILD_SUCCESS
  after_script:
  - scripts/ci/report-gerrit.sh
  cache:
    key: "ci:build-1"
    paths:
    - .mod/
  artifacts:
    paths:
    - artifacts/
