stages:
- verify
- test
- package
- deploy
- dev
- sandbox
- staging
- production


variables:
  PROJECT_DIR: $(echo $CI_PROJECT_DIR | sed "s/$CI_PROJECT_NAME//g" | sed 's:/*$::')
  PROJECT_LOG: "*:0"

.go-cache:
  cache:
    paths: [".cache"]
  before_script:
    - mkdir -p .cache
    - export GOPATH="$CI_PROJECT_DIR/.cache"

# verify:import:
#   extends: .verify
#   script:
#     - time scripts/verify-imports.sh

# verify:lint:
#   extends: .verify
#   script:
#     - time scripts/ci/verify-lint.sh

# verify:generate:
#   extends: .verify
#   script:
#     - time scripts/ci/verify-generate.sh

test:
  image: golang:1.15
  extends: .go-cache
  stage: test
  services:
    - postgres:12.2-alpine
    - redis:latest
  variables:
    POSTGRES_DB: test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "postgres"
    POSTGRES_HOST_AUTH_METHOD: trust
  # dependencies: 
  #   - verify:import
  #   - verify:lint
  #   - verify:generate
  except: ["tags"]
  script:
    - echo $PROJECT_DIR
    - time go run ./scripts/init_testdb/main.go -drop
    - time scripts/ci/test-all.sh simple

include: 'ci/**.yml'
