stages:
- build
- report

variables:
  ETOPDIR: /etop.vn
  POSTGRES_USER: postgres
  POSTGRES_DB: test
  POSTGRES_PASSWORD: postgres

before_script:
- mkdir -p artifacts
- mkdir -p /etop.vn
- ln -s $PWD /etop.vn/backend

report-gerrit-changes-running:
  stage: build
  tags: [go]
  image: olvrng/alpine-toolbox
  before_script: []
  script:
  - scripts/ci/report-gerrit.sh running

build:
  stage: build
  tags: [go]
  image: golang:1.12
  services:
  - postgres:9.6-alpine
  - redis:alpine
  script:
  - scripts/ci/cache-load.sh
  - scripts/verify-imports.sh
  - go run ./scripts/init_testdb/main.go -drop
  - scripts/ci/test-all.sh
  - scripts/ci/cache-save.sh
  - touch artifacts/BUILD_SUCCESS
  cache:
    key: "ci:build"
    paths:
    - .mod/
  artifacts:
    paths:
    - artifacts/

report-gerrit-changes:
  stage: report
  when: always
  tags: [go]
  image: olvrng/alpine-toolbox
  before_script: []
  script:
  - scripts/ci/report-gerrit.sh
  artifacts:
    paths:
    - artifacts/
