rules:
- selectorRegexp: "o[.]o"
  allowedPrefixes:
  - o.o/api
  - o.o/backend/cmd/etop-server/config
  - o.o/backend/com
  - o.o/backend/pb
  - o.o/backend/pkg/common
  - o.o/backend/pkg/etc
  - o.o/backend/pkg/etop-handler/intctl
  - o.o/backend/pkg/etop-handler/webhook/sender
  - o.o/backend/pkg/etop/api
  - o.o/backend/pkg/etop/authorize
  - o.o/backend/pkg/etop/cache
  - o.o/backend/pkg/etop/config
  - o.o/backend/pkg/etop/eventstream
  - o.o/backend/pkg/etop/logic
  - o.o/backend/pkg/etop/model
  - o.o/backend/pkg/etop/sqlstore
  - o.o/backend/pkg/integration
  - o.o/backend/pkg/models
  - o.o/backend/pkg/notifier/model
  - o.o/backend/pkg/services
  - o.o/backend/zexp/api
  - o.o/capi
  - o.o/common
  # TODO: remove this
  - o.o/backend/tools/pkg/acl
  - o.o/backend/cogs
