CREATE TABLE public.account (
                              id bigint NOT NULL,
                              name text NOT NULL,
                              deleted_at timestamp with time zone,
                              image_url text,
                              type public.account_type,
                              rid bigint NOT NULL,
                              url_slug text,
                              owner_id bigint
);

CREATE TABLE public.account_auth (
                                   auth_key text NOT NULL,
                                   account_id bigint NOT NULL,
                                   status smallint,
                                   roles text[],
                                   permissions text[],
                                   created_at timestamp with time zone,
                                   updated_at timestamp with time zone,
                                   deleted_at timestamp with time zone,
                                   rid bigint NOT NULL
);

CREATE TABLE public.account_user (
                                   account_id bigint NOT NULL,
                                   user_id bigint NOT NULL,
                                   status smallint NOT NULL,
                                   created_at timestamp with time zone,
                                   updated_at timestamp with time zone,
                                   roles text[],
                                   permissions text[],
                                   deleted_at timestamp with time zone,
                                   rid bigint NOT NULL,
                                   full_name text,
                                   short_name text,
                                   "position" text,
                                   response_status smallint,
                                   invitation_sent_at timestamp with time zone,
                                   invitation_sent_by bigint,
                                   invitation_accepted_at timestamp with time zone,
                                   invitation_rejected_at timestamp with time zone,
                                   disabled_at timestamp with time zone,
                                   disabled_by bigint,
                                   disable_reason text
);

CREATE TABLE public.address (
                              id bigint NOT NULL,
                              country text DEFAULT 'VN'::text,
                              province_code text,
                              province text,
                              district_code text,
                              district text,
                              ward text,
                              ward_code text,
                              address1 text,
                              is_default boolean DEFAULT false,
                              type public.address_type,
                              account_id bigint,
                              created_at timestamp with time zone NOT NULL,
                              updated_at timestamp with time zone NOT NULL,
                              full_name text,
                              first_name text,
                              last_name text,
                              email text,
                              "position" text,
                              city text,
                              zip text,
                              address2 text,
                              phone text,
                              company text,
                              notes jsonb,
                              rid bigint NOT NULL,
                              coordinates jsonb
);

CREATE TABLE public.affiliate (
                                id bigint NOT NULL,
                                rid bigint,
                                name text NOT NULL,
                                owner_id bigint NOT NULL,
                                status smallint,
                                is_test smallint DEFAULT '0'::smallint,
                                phone text,
                                email text,
                                created_at timestamp with time zone,
                                updated_at timestamp with time zone,
                                deleted_at timestamp with time zone,
                                bank_account jsonb
);

CREATE TABLE public.code (
                           code text NOT NULL,
                           type public.code_type NOT NULL,
                           created_at timestamp with time zone
);

CREATE TABLE public.connection (
                                 id bigint NOT NULL,
                                 name text,
                                 status smallint,
                                 partner_id bigint,
                                 created_at timestamp with time zone,
                                 updated_at timestamp with time zone,
                                 deleted_at timestamp with time zone,
                                 driver_config jsonb,
                                 driver text,
                                 connection_type text,
                                 connection_subtype text,
                                 connection_method text,
                                 connection_provider text,
                                 etop_affiliate_account jsonb,
                                 code text,
                                 image_url text,
                                 rid bigint NOT NULL
);

CREATE TABLE public.credit (
                             id bigint NOT NULL,
                             rid bigint NOT NULL,
                             amount bigint,
                             shop_id bigint,
                             supplier_id bigint,
                             created_at timestamp with time zone,
                             updated_at timestamp with time zone,
                             paid_at timestamp with time zone,
                             type public.account_type,
                             status smallint
);

CREATE TABLE public.district (
                               code text NOT NULL,
                               province_code text NOT NULL,
                               urban smallint NOT NULL,
                               name text NOT NULL,
                               ghn_id bigint,
                               vtpost_id bigint
);

CREATE TABLE public.export_attempt (
                                     id text NOT NULL,
                                     user_id bigint NOT NULL,
                                     account_id bigint NOT NULL,
                                     export_type text NOT NULL,
                                     filename text,
                                     stored_file text,
                                     download_url text,
                                     request_query text,
                                     mime_type text,
                                     status smallint NOT NULL,
                                     errors jsonb,
                                     error jsonb,
                                     n_total bigint,
                                     n_exported bigint,
                                     n_error bigint,
                                     created_at timestamp with time zone,
                                     deleted_at timestamp with time zone,
                                     started_at timestamp with time zone,
                                     done_at timestamp with time zone,
                                     expires_at timestamp with time zone
);

CREATE TABLE public.external_account_ahamove (
                                               id bigint NOT NULL,
                                               owner_id bigint NOT NULL,
                                               phone text NOT NULL,
                                               name text NOT NULL,
                                               external_token text,
                                               external_verified boolean,
                                               created_at timestamp with time zone,
                                               updated_at timestamp with time zone,
                                               external_created_at timestamp with time zone,
                                               last_send_verified_at timestamp with time zone,
                                               external_ticket_id text,
                                               external_id text,
                                               id_card_front_img text,
                                               id_card_back_img text,
                                               portrait_img text,
                                               uploaded_at timestamp with time zone,
                                               fanpage_url text,
                                               business_license_imgs text[],
                                               website_url text,
                                               company_imgs text[],
                                               external_data_verified jsonb
);

CREATE TABLE public.fulfillment (
                                  id bigint NOT NULL,
                                  order_id bigint NOT NULL,
                                  lines jsonb,
                                  variant_ids bigint[] NOT NULL,
                                  type_from public.fulfillment_endpoint NOT NULL,
                                  type_to public.fulfillment_endpoint NOT NULL,
                                  address_from jsonb NOT NULL,
                                  address_to jsonb NOT NULL,
                                  shop_id bigint NOT NULL,
                                  supplier_id bigint,
                                  total_items bigint NOT NULL,
                                  total_weight bigint NOT NULL,
                                  basket_value bigint NOT NULL,
                                  total_cod_amount bigint NOT NULL,
                                  shipping_fee_customer bigint NOT NULL,
                                  shipping_fee_shop bigint NOT NULL,
                                  external_shipping_fee bigint NOT NULL,
                                  created_at timestamp with time zone NOT NULL,
                                  updated_at timestamp with time zone NOT NULL,
                                  shipping_cancelled_at timestamp with time zone,
                                  cancel_reason text,
                                  closed_at timestamp with time zone,
                                  shipping_provider public.shipping_provider NOT NULL,
                                  shipping_code text,
                                  shipping_note text,
                                  external_shipping_id text,
                                  external_shipping_code text,
                                  external_shipping_created_at timestamp with time zone,
                                  external_shipping_updated_at timestamp with time zone,
                                  external_shipping_cancelled_at timestamp with time zone,
                                  external_shipping_delivered_at timestamp with time zone,
                                  external_shipping_returned_at timestamp with time zone,
                                  external_shipping_state text,
                                  external_shipping_status smallint,
                                  external_shipping_data jsonb,
                                  shipping_state public.shipping_state,
                                  status smallint,
                                  sync_status smallint,
                                  rid bigint NOT NULL,
                                  sync_states jsonb,
                                  shipping_delivered_at timestamp with time zone,
                                  shipping_returned_at timestamp with time zone,
                                  external_shipping_closed_at timestamp with time zone,
                                  supplier_confirm smallint,
                                  shop_confirm smallint,
                                  last_sync_at timestamp with time zone,
                                  expected_delivery_at timestamp with time zone,
                                  money_transaction_id bigint,
                                  cod_etop_transfered_at timestamp with time zone,
                                  shipping_fee_shop_transfered_at timestamp with time zone,
                                  provider_shipping_fee_lines jsonb,
                                  shipping_fee_shop_lines jsonb,
                                  etop_discount bigint,
                                  shipping_status smallint,
                                  etop_fee_adjustment bigint,
                                  etop_payment_status smallint NOT NULL,
                                  address_to_province_code text,
                                  address_to_district_code text,
                                  address_to_ward_code text,
                                  provider_service_id text,
                                  expected_pick_at timestamp with time zone,
                                  confirm_status smallint NOT NULL,
                                  shipping_fee_main bigint NOT NULL,
                                  shipping_fee_return bigint NOT NULL,
                                  shipping_fee_insurance bigint NOT NULL,
                                  shipping_fee_adjustment bigint NOT NULL,
                                  shipping_fee_cods bigint NOT NULL,
                                  shipping_fee_info_change bigint NOT NULL,
                                  shipping_fee_other bigint NOT NULL,
                                  external_shipping_state_code text,
                                  money_transaction_shipping_external_id bigint,
                                  total_discount bigint NOT NULL,
                                  total_amount bigint NOT NULL,
                                  external_shipping_logs jsonb,
                                  partner_id bigint,
                                  external_shipping_sub_state text,
                                  external_shipping_note text,
                                  try_on public.try_on,
                                  external_shipping_name text,
                                  shipping_service_fee bigint,
                                  original_cod_amount bigint,
                                  address_return jsonb,
                                  include_insurance boolean,
                                  admin_note text,
                                  is_partial_delivery boolean,
                                  shipping_fee_discount bigint,
                                  shipping_created_at timestamp with time zone,
                                  shipping_picking_at timestamp with time zone,
                                  shipping_holding_at timestamp with time zone,
                                  shipping_delivering_at timestamp with time zone,
                                  shipping_returning_at timestamp with time zone,
                                  etop_adjusted_shipping_fee_main bigint,
                                  etop_price_rule boolean,
                                  actual_compensation_amount bigint,
                                  delivery_route text,
                                  created_by bigint,
                                  shipping_type smallint,
                                  connection_id bigint,
                                  connection_method text,
                                  shop_carrier_id bigint,
                                  shipping_service_name text,
                                  gross_weight bigint,
                                  chargeable_weight bigint,
                                  length bigint,
                                  width bigint,
                                  height bigint,
                                  external_affiliate_id text,
                                  CONSTRAINT type_from_supplier_id CHECK (((type_from = 'supplier'::public.fulfillment_endpoint) = (supplier_id IS NOT NULL)))
);

CREATE TABLE public.import_attempt (
                                     id bigint NOT NULL,
                                     user_id bigint NOT NULL,
                                     account_id bigint NOT NULL,
                                     original_file text NOT NULL,
                                     stored_file text,
                                     type public.import_type NOT NULL,
                                     n_created smallint NOT NULL,
                                     n_updated smallint NOT NULL,
                                     n_error smallint NOT NULL,
                                     status smallint NOT NULL,
                                     error_type text,
                                     errors jsonb,
                                     duration_ms bigint NOT NULL,
                                     created_at timestamp with time zone NOT NULL,
                                     rid bigint NOT NULL
);

CREATE TABLE public.inventory_variant (
                                        shop_id bigint,
                                        variant_id bigint,
                                        quantity_on_hand bigint,
                                        quantity_picked bigint,
                                        cost_price bigint,
                                        created_at timestamp with time zone,
                                        updated_at timestamp with time zone,
                                        rid bigint NOT NULL
);

CREATE TABLE public.inventory_voucher (
                                        title character varying,
                                        shop_id bigint,
                                        id bigint,
                                        created_by bigint,
                                        updated_by bigint,
                                        status smallint,
                                        trader_id bigint,
                                        total_amount bigint,
                                        type public.inventory_voucher_type,
                                        created_at timestamp with time zone,
                                        updated_at timestamp with time zone,
                                        confirmed_at timestamp with time zone,
                                        cancelled_at timestamp with time zone,
                                        cancel_reason character varying,
                                        lines jsonb,
                                        ref_id bigint,
                                        ref_type text,
                                        code_norm bigint,
                                        code text,
                                        trader jsonb,
                                        variant_ids bigint[],
                                        ref_code text,
                                        product_ids bigint[],
                                        rid bigint NOT NULL
);

CREATE TABLE public.invitation (
                                 id bigint NOT NULL,
                                 account_id bigint NOT NULL,
                                 email text,
                                 roles text[],
                                 token text,
                                 status smallint,
                                 invited_by bigint NOT NULL,
                                 accepted_at timestamp with time zone,
                                 rejected_at timestamp with time zone,
                                 expires_at timestamp with time zone,
                                 created_at timestamp with time zone,
                                 updated_at timestamp with time zone,
                                 deleted_at timestamp with time zone,
                                 rid bigint NOT NULL,
                                 full_name text,
                                 short_name text,
                                 "position" text,
                                 phone text
);

CREATE TABLE public.money_transaction_shipping (
                                                 id bigint NOT NULL,
                                                 shop_id bigint,
                                                 supplier_id bigint,
                                                 status smallint,
                                                 total_cod bigint NOT NULL,
                                                 total_orders bigint NOT NULL,
                                                 code text NOT NULL,
                                                 created_at timestamp with time zone,
                                                 updated_at timestamp with time zone,
                                                 closed_at timestamp with time zone,
                                                 money_transaction_shipping_external_id bigint,
                                                 provider public.shipping_provider,
                                                 etop_transfered_at timestamp with time zone,
                                                 total_amount bigint,
                                                 rid bigint NOT NULL,
                                                 confirmed_at timestamp with time zone,
                                                 money_transaction_shipping_etop_id bigint,
                                                 bank_account json,
                                                 note text,
                                                 invoice_number text,
                                                 type text
);

CREATE TABLE public.money_transaction_shipping_etop (
                                                      id bigint NOT NULL,
                                                      code text NOT NULL,
                                                      total_cod bigint NOT NULL,
                                                      total_orders bigint NOT NULL,
                                                      total_amount bigint NOT NULL,
                                                      total_fee bigint NOT NULL,
                                                      total_money_transaction bigint NOT NULL,
                                                      created_at timestamp with time zone,
                                                      updated_at timestamp with time zone,
                                                      confirmed_at timestamp with time zone,
                                                      status smallint,
                                                      bank_account jsonb,
                                                      note text,
                                                      invoice_number text
);

CREATE TABLE public.money_transaction_shipping_external (
                                                          id bigint NOT NULL,
                                                          code text NOT NULL,
                                                          total_cod bigint NOT NULL,
                                                          total_orders bigint NOT NULL,
                                                          created_at timestamp with time zone,
                                                          updated_at timestamp with time zone,
                                                          status smallint,
                                                          external_paid_at timestamp with time zone,
                                                          provider public.shipping_provider NOT NULL,
                                                          bank_account json,
                                                          note text,
                                                          invoice_number text
);

CREATE TABLE public.money_transaction_shipping_external_line (
                                                               id bigint NOT NULL,
                                                               external_code text NOT NULL,
                                                               external_total_cod bigint NOT NULL,
                                                               external_created_at timestamp with time zone,
                                                               external_closed_at timestamp with time zone,
                                                               external_customer text,
                                                               external_address text,
                                                               etop_fulfillment_id_raw text,
                                                               etop_fulfillment_id bigint,
                                                               note text,
                                                               money_transaction_shipping_external_id bigint NOT NULL,
                                                               created_at timestamp with time zone,
                                                               updated_at timestamp with time zone,
                                                               import_error jsonb,
                                                               external_total_shipping_fee bigint
);

CREATE TABLE public."order" (
                              id bigint NOT NULL,
                              rid bigint NOT NULL,
                              shop_id bigint NOT NULL,
                              code text NOT NULL,
                              product_ids bigint[],
                              variant_ids bigint[],
                              supplier_ids bigint[],
                              currency text,
                              payment_method text,
                              customer jsonb,
                              customer_address jsonb,
                              billing_address jsonb,
                              shipping_address jsonb,
                              customer_phone text,
                              customer_email text,
                              created_at timestamp with time zone NOT NULL,
                              processed_at timestamp with time zone,
                              updated_at timestamp with time zone NOT NULL,
                              closed_at timestamp with time zone,
                              confirmed_at timestamp with time zone,
                              cancelled_at timestamp with time zone,
                              cancel_reason text,
                              customer_confirm smallint,
                              external_confirm smallint,
                              shop_confirm smallint NOT NULL,
                              confirm_status smallint,
                              processing_status public.processing_status,
                              status smallint NOT NULL,
                              lines jsonb,
                              discounts jsonb,
                              total_items bigint,
                              basket_value bigint,
                              total_weight bigint,
                              total_tax bigint,
                              total_discount bigint,
                              total_amount bigint,
                              order_note text,
                              shop_note text,
                              shipping_note text,
                              order_source_id bigint,
                              order_source_type public.order_source_type NOT NULL,
                              external_order_id text,
                              fulfillment_shipping_status smallint NOT NULL,
                              customer_payment_status smallint,
                              shop_shipping_fee bigint,
                              reference_url text,
                              external_order_source text,
                              shop_address jsonb,
                              shop_shipping jsonb,
                              shop_cod bigint,
                              is_outside_etop boolean DEFAULT false,
                              ghn_note_code public.ghn_note_code,
                              ed_code text,
                              order_discount bigint,
                              etop_payment_status smallint NOT NULL,
                              fulfillment_shipping_states text[],
                              fulfillment_payment_statuses smallint[],
                              fulfillment_shipping_codes text[],
                              customer_name text,
                              customer_name_norm tsvector,
                              product_name_norm tsvector,
                              fulfillment_sync_statuses smallint[],
                              partner_id bigint,
                              try_on public.try_on,
                              total_fee bigint,
                              fee_lines jsonb,
                              external_url text,
                              fulfillment_type smallint,
                              fulfillment_ids bigint[],
                              external_meta jsonb,
                              trading_shop_id bigint,
                              payment_status smallint,
                              payment_id bigint,
                              referral_meta jsonb,
                              customer_id bigint,
                              created_by bigint,
                              fulfillment_statuses smallint[],
                              CONSTRAINT customer_email_notempty CHECK (((customer_email IS NULL) OR (customer_email <> ''::text))),
                              CONSTRAINT payment_price CHECK (((COALESCE(order_discount, 0) >= 0) AND (COALESCE(order_discount, 0) <= total_discount))),
                              CONSTRAINT total_amount CHECK ((total_amount = ((basket_value - total_discount) + COALESCE(total_fee, shop_shipping_fee))))
);

CREATE TABLE public.order_line (
                                 rid bigint NOT NULL,
                                 order_id bigint NOT NULL,
                                 product_id bigint,
                                 variant_id bigint,
                                 supplier_id bigint,
                                 external_variant_id text,
                                 external_supplier_order_id text,
                                 product_name text,
                                 supplier_name text,
                                 image_url text,
                                 created_at timestamp with time zone,
                                 updated_at timestamp with time zone,
                                 closed_at timestamp with time zone,
                                 confirmed_at timestamp with time zone,
                                 cancelled_at timestamp with time zone,
                                 cancel_reason text,
                                 supplier_confirm smallint,
                                 status smallint,
                                 weight bigint NOT NULL,
                                 quantity bigint NOT NULL,
                                 wholesale_price_0 bigint,
                                 wholesale_price bigint,
                                 list_price bigint NOT NULL,
                                 retail_price bigint NOT NULL,
                                 payment_price bigint NOT NULL,
                                 line_amount bigint NOT NULL,
                                 total_discount bigint NOT NULL,
                                 total_line_amount bigint NOT NULL,
                                 requires_shipping boolean,
                                 is_outside_etop boolean DEFAULT false NOT NULL,
                                 code text NOT NULL,
                                 shop_id bigint NOT NULL,
                                 is_free boolean,
                                 meta_fields jsonb,
                                 CONSTRAINT payment_price CHECK (((payment_price >= 0) AND (payment_price <= retail_price))),
                                 CONSTRAINT quantity CHECK ((quantity > 0)),
                                 CONSTRAINT total_discount CHECK (((total_discount >= 0) AND (total_discount = ((retail_price - payment_price) * quantity))))
);

CREATE TABLE public.partner (
                              id bigint NOT NULL,
                              rid bigint NOT NULL,
                              name text NOT NULL,
                              public_name text NOT NULL,
                              owner_id bigint NOT NULL,
                              status smallint NOT NULL,
                              is_test smallint NOT NULL,
                              phone text,
                              email text,
                              website_url text,
                              image_url text,
                              created_at timestamp with time zone,
                              updated_at timestamp with time zone,
                              deleted_at timestamp with time zone,
                              contact_persons jsonb,
                              recognized_hosts text[],
                              redirect_urls text[],
                              available_from_etop boolean,
                              available_from_etop_config jsonb,
                              white_label_key text
);

CREATE TABLE public.partner_relation (
                                       partner_id bigint NOT NULL,
                                       subject_id bigint NOT NULL,
                                       subject_type public.subject_type NOT NULL,
                                       external_subject_id text,
                                       nonce bigint,
                                       status smallint NOT NULL,
                                       roles text[],
                                       permissions text[],
                                       created_at timestamp with time zone,
                                       updated_at timestamp with time zone,
                                       deleted_at timestamp with time zone,
                                       rid bigint NOT NULL,
                                       auth_key text NOT NULL
);


CREATE TABLE public.payment (
                              id bigint NOT NULL,
                              amount bigint,
                              status smallint,
                              state text,
                              payment_provider text,
                              external_trans_id text,
                              external_data jsonb,
                              created_at timestamp without time zone,
                              updated_at timestamp without time zone,
                              rid bigint NOT NULL
);

CREATE TABLE public.product_shop_collection (
                                              product_id bigint NOT NULL,
                                              shop_id bigint,
                                              collection_id bigint NOT NULL,
                                              created_at timestamp with time zone,
                                              updated_at timestamp with time zone,
                                              status smallint,
                                              rid bigint NOT NULL
);

CREATE TABLE public.province (
                               code text NOT NULL,
                               region public.province_region NOT NULL,
                               name text NOT NULL,
                               vtpost_id bigint
);

CREATE TABLE public.purchase_order (
                                     id bigint NOT NULL,
                                     shop_id bigint NOT NULL,
                                     supplier_id bigint NOT NULL,
                                     supplier jsonb,
                                     basket_value bigint,
                                     total_discount bigint,
                                     total_amount bigint,
                                     paid_amount bigint,
                                     code text NOT NULL,
                                     code_norm bigint,
                                     note text,
                                     status smallint,
                                     variant_ids bigint[],
                                     lines jsonb,
                                     cancelled_reason text,
                                     created_by bigint NOT NULL,
                                     created_at timestamp with time zone,
                                     updated_at timestamp with time zone,
                                     confirmed_at timestamp with time zone,
                                     cancelled_at timestamp with time zone,
                                     deleted_at timestamp with time zone,
                                     rid bigint NOT NULL,
                                     supplier_full_name_norm text,
                                     supplier_phone_norm text,
                                     discount_lines jsonb,
                                     total_fee bigint,
                                     fee_lines jsonb
);

CREATE TABLE public.purchase_refund (
                                      id bigint NOT NULL,
                                      shop_id bigint NOT NULL,
                                      purchase_order_id bigint NOT NULL,
                                      note text,
                                      code_norm bigint,
                                      code text,
                                      supplier_id bigint,
                                      lines jsonb,
                                      created_at timestamp with time zone,
                                      updated_at timestamp with time zone,
                                      cancelled_at timestamp with time zone,
                                      confirmed_at timestamp with time zone,
                                      created_by bigint NOT NULL,
                                      updated_by bigint NOT NULL,
                                      total_amount bigint,
                                      basket_value bigint,
                                      cancel_reason text,
                                      status smallint,
                                      adjustment_lines jsonb,
                                      total_adjustment bigint,
                                      rid bigint NOT NULL
);

CREATE TABLE public.receipt (
                              id bigint NOT NULL,
                              shop_id bigint NOT NULL,
                              trader_id bigint,
                              created_by bigint,
                              code text NOT NULL,
                              title text NOT NULL,
                              description text,
                              amount bigint,
                              status smallint,
                              type public.receipt_type NOT NULL,
                              lines jsonb,
                              ref_ids bigint[],
                              created_at timestamp with time zone,
                              updated_at timestamp with time zone,
                              deleted_at timestamp with time zone,
                              rid bigint NOT NULL,
                              shop_ledger_id bigint,
                              created_type public.receipt_created_type,
                              ledger_id bigint,
                              cancelled_reason text,
                              code_norm bigint,
                              paid_at timestamp with time zone,
                              confirmed_at timestamp with time zone,
                              cancelled_at timestamp with time zone,
                              ref_type public.receipt_ref_type,
                              trader jsonb,
                              trader_full_name_norm tsvector,
                              trader_type public.trader_type,
                              trader_phone_norm tsvector
);

CREATE TABLE public.refund (
                             id bigint NOT NULL,
                             shop_id bigint NOT NULL,
                             order_id bigint NOT NULL,
                             note text,
                             code_norm bigint,
                             code text,
                             customer_id bigint,
                             lines jsonb,
                             created_at timestamp with time zone,
                             updated_at timestamp with time zone,
                             cancelled_at timestamp with time zone,
                             confirmed_at timestamp with time zone,
                             created_by bigint NOT NULL,
                             updated_by bigint NOT NULL,
                             total_amount bigint,
                             basket_value bigint,
                             cancel_reason text,
                             status smallint,
                             adjustment_lines jsonb,
                             total_adjustment bigint,
                             rid bigint NOT NULL
);

CREATE TABLE public.shipnow_fulfillment (
                                          id bigint NOT NULL,
                                          shop_id bigint,
                                          partner_id bigint,
                                          order_ids bigint[],
                                          pickup_address jsonb,
                                          carrier text,
                                          shipping_service_code text,
                                          shipping_service_fee bigint,
                                          chargeable_weight bigint,
                                          gross_weight bigint,
                                          basket_value bigint,
                                          cod_amount bigint,
                                          shipping_note text,
                                          request_pickup_at timestamp with time zone,
                                          delivery_points jsonb,
                                          status smallint,
                                          shipping_state text,
                                          sync_status smallint,
                                          sync_states jsonb,
                                          last_sync_at timestamp with time zone,
                                          created_at timestamp with time zone,
                                          updated_at timestamp with time zone,
                                          confirm_status smallint,
                                          shipping_status smallint,
                                          shipping_code text,
                                          fee_lines jsonb,
                                          carrier_fee_lines jsonb,
                                          total_fee bigint,
                                          shipping_created_at timestamp with time zone,
                                          etop_payment_status smallint,
                                          cod_etop_transfered_at timestamp with time zone,
                                          shipping_picking_at timestamp with time zone,
                                          shipping_delivering_at timestamp with time zone,
                                          shipping_delivered_at timestamp with time zone,
                                          shipping_cancelled_at timestamp with time zone,
                                          shipping_service_name text,
                                          shipping_service_description text,
                                          cancel_reason text,
                                          shipping_shared_link text,
                                          address_to_province_code text,
                                          address_to_district_code text,
                                          rid bigint NOT NULL
);

CREATE TABLE public.shipping_source (
                                      id bigint NOT NULL,
                                      name text,
                                      type public.shipping_provider NOT NULL,
                                      created_at timestamp with time zone,
                                      updated_at timestamp with time zone,
                                      rid bigint,
                                      username text
);

CREATE TABLE public.shipping_source_internal (
                                               id bigint NOT NULL,
                                               rid bigint,
                                               last_sync_at timestamp with time zone,
                                               created_at timestamp with time zone,
                                               updated_at timestamp with time zone,
                                               secret jsonb,
                                               access_token text,
                                               expires_at timestamp with time zone
);

CREATE TABLE public.shop (
                           id bigint NOT NULL,
                           rid bigint NOT NULL,
                           name text NOT NULL,
                           owner_id bigint NOT NULL,
                           status smallint NOT NULL,
                           product_source_id bigint,
                           created_at timestamp with time zone DEFAULT date_trunc('second'::text, now()) NOT NULL,
                           updated_at timestamp with time zone NOT NULL,
                           rules jsonb,
                           is_test smallint DEFAULT '0'::smallint NOT NULL,
                           image_url text,
                           phone text,
                           website_url text,
                           email text,
                           deleted_at timestamp with time zone,
                           address_id bigint,
                           bank_account jsonb,
                           contact_persons jsonb,
                           order_source_id bigint,
                           ship_to_address_id bigint,
                           ship_from_address_id bigint,
                           code text,
                           auto_create_ffm boolean DEFAULT false,
                           ghn_note_code public.ghn_note_code,
                           try_on public.try_on NOT NULL,
                           recognized_hosts text[],
                           company_info jsonb,
                           money_transaction_rrule text,
                           survey_info jsonb,
                           shipping_service_select_strategy jsonb,
                           inventory_overstock boolean,
                           wl_partner_id bigint
);

CREATE TABLE public.shop_brand (
                                 shop_id bigint,
                                 id bigint,
                                 description text,
                                 brand_name text,
                                 updated_at timestamp with time zone,
                                 created_at timestamp with time zone,
                                 deleted_at timestamp with time zone,
                                 rid bigint NOT NULL,
                                 external_id text,
                                 partner_id bigint
);

CREATE TABLE public.shop_carrier (
                                   id bigint NOT NULL,
                                   shop_id bigint,
                                   full_name text,
                                   note text,
                                   status smallint NOT NULL,
                                   created_at timestamp with time zone,
                                   updated_at timestamp with time zone,
                                   deleted_at timestamp with time zone,
                                   rid bigint NOT NULL
);

CREATE TABLE public.shop_category (
                                    id bigint NOT NULL,
                                    rid bigint NOT NULL,
                                    product_source_id bigint,
                                    product_source_type public.product_source_type,
                                    supplier_id bigint,
                                    parent_id bigint,
                                    name text,
                                    status smallint NOT NULL,
                                    created_at timestamp with time zone,
                                    updated_at timestamp with time zone,
                                    deleted_at timestamp with time zone,
                                    shop_id bigint,
                                    external_id text,
                                    external_parent_id text,
                                    partner_id bigint
);

CREATE TABLE public.shop_collection (
                                      id bigint NOT NULL,
                                      rid bigint NOT NULL,
                                      shop_id bigint NOT NULL,
                                      name text,
                                      description text,
                                      desc_html text,
                                      short_desc text,
                                      created_at timestamp with time zone,
                                      updated_at timestamp with time zone,
                                      deleted_at timestamp with time zone,
                                      partner_id bigint,
                                      external_id text
);

CREATE TABLE public.shop_connection (
                                      shop_id bigint,
                                      connection_id bigint,
                                      token text,
                                      token_expires_at timestamp with time zone,
                                      status smallint,
                                      connection_states jsonb,
                                      is_global boolean,
                                      created_at timestamp with time zone,
                                      updated_at timestamp with time zone,
                                      deleted_at timestamp with time zone,
                                      external_data jsonb,
                                      rid bigint NOT NULL
);

CREATE TABLE public.shop_customer (
                                    id bigint NOT NULL,
                                    shop_id bigint,
                                    code text,
                                    full_name text,
                                    gender public.gender_type,
                                    type public.customer_type,
                                    birthday date,
                                    note text,
                                    phone text,
                                    email text,
                                    status smallint NOT NULL,
                                    created_at timestamp with time zone,
                                    updated_at timestamp with time zone,
                                    deleted_at timestamp with time zone,
                                    rid bigint NOT NULL,
                                    full_name_norm tsvector,
                                    phone_norm tsvector,
                                    code_norm bigint,
                                    external_id text,
                                    external_code text,
                                    partner_id bigint
);

CREATE TABLE public.shop_customer_group (
                                          id bigint NOT NULL,
                                          name text,
                                          created_at timestamp with time zone,
                                          updated_at timestamp with time zone,
                                          deleted_at timestamp with time zone,
                                          shop_id bigint,
                                          rid bigint NOT NULL,
                                          partner_id bigint
);

CREATE TABLE public.shop_customer_group_customer (
                                                   customer_id bigint NOT NULL,
                                                   group_id bigint NOT NULL,
                                                   created_at timestamp with time zone,
                                                   updated_at timestamp with time zone,
                                                   rid bigint NOT NULL
);

CREATE TABLE public.shop_ledger (
                                  id bigint NOT NULL,
                                  shop_id bigint,
                                  name text NOT NULL,
                                  bank_account jsonb,
                                  status smallint,
                                  note text,
                                  type public.shop_ledger_type NOT NULL,
                                  created_by bigint,
                                  created_at timestamp with time zone,
                                  updated_at timestamp with time zone,
                                  deleted_at timestamp with time zone,
                                  rid bigint NOT NULL
);

CREATE TABLE public.shop_product (
                                   shop_id bigint NOT NULL,
                                   product_id bigint NOT NULL,
                                   rid bigint NOT NULL,
                                   collection_id bigint,
                                   name text,
                                   description text,
                                   desc_html text,
                                   short_desc text,
                                   retail_price bigint,
                                   tags text[],
                                   created_at timestamp with time zone NOT NULL,
                                   updated_at timestamp with time zone NOT NULL,
                                   note text,
                                   image_urls text[],
                                   status smallint,
                                   name_norm tsvector,
                                   deleted_at timestamp with time zone,
                                   code text,
                                   name_norm_ua text,
                                   category_id bigint,
                                   cost_price bigint,
                                   list_price bigint,
                                   unit text,
                                   product_type text,
                                   meta_fields jsonb,
                                   brand_id bigint,
                                   external_id text,
                                   external_code text,
                                   partner_id bigint,
                                   code_norm bigint,
                                   external_brand_id text,
                                   external_category_id text
);

CREATE TABLE public.shop_product_collection (
                                              product_id bigint NOT NULL,
                                              collection_id bigint NOT NULL,
                                              shop_id bigint,
                                              status smallint,
                                              created_at timestamp with time zone,
                                              updated_at timestamp with time zone,
                                              partner_id bigint,
                                              external_collection_id text,
                                              external_product_id text,
                                              deleted_at timestamp with time zone,
                                              rid bigint NOT NULL
);

CREATE TABLE public.shop_stocktake (
                                     id bigint NOT NULL,
                                     shop_id bigint,
                                     created_by bigint,
                                     updated_by bigint,
                                     created_at timestamp with time zone,
                                     updated_at timestamp with time zone,
                                     confirmed_at timestamp with time zone,
                                     cancelled_at timestamp with time zone,
                                     variant_ids bigint[],
                                     total_quantity bigint,
                                     status smallint,
                                     lines jsonb,
                                     code text,
                                     code_norm bigint,
                                     note text,
                                     cancel_reason text,
                                     product_ids bigint[],
                                     type text,
                                     rid bigint NOT NULL
);

CREATE TABLE public.shop_supplier (
                                    id bigint NOT NULL,
                                    shop_id bigint NOT NULL,
                                    full_name text,
                                    note text,
                                    status smallint,
                                    created_at timestamp with time zone,
                                    updated_at timestamp with time zone,
                                    deleted_at timestamp with time zone,
                                    rid bigint NOT NULL,
                                    phone text,
                                    email text,
                                    company_name text,
                                    tax_number text,
                                    headquater_address text,
                                    full_name_norm tsvector,
                                    phone_norm tsvector,
                                    code_norm bigint,
                                    code text,
                                    company_name_norm tsvector
);

CREATE TABLE public.shop_trader (
                                  id bigint NOT NULL,
                                  shop_id bigint,
                                  rid bigint NOT NULL,
                                  type public.trader_type NOT NULL,
                                  deleted_at timestamp with time zone
);

CREATE TABLE public.shop_trader_address (
                                          id bigint NOT NULL,
                                          shop_id bigint NOT NULL,
                                          trader_id bigint NOT NULL,
                                          full_name text,
                                          phone text,
                                          email text,
                                          company text,
                                          district_code text,
                                          ward_code text,
                                          city text,
                                          address1 text,
                                          address2 text,
                                          "position" text,
                                          note text,
                                          "primary" boolean,
                                          status smallint NOT NULL,
                                          coordinates jsonb,
                                          created_at timestamp with time zone,
                                          updated_at timestamp with time zone,
                                          deleted_at timestamp with time zone,
                                          rid bigint NOT NULL,
                                          is_default boolean,
                                          partner_id bigint
);

CREATE TABLE public.shop_variant (
                                   shop_id bigint NOT NULL,
                                   variant_id bigint NOT NULL,
                                   rid bigint NOT NULL,
                                   collection_id bigint,
                                   name text,
                                   description text,
                                   desc_html text,
                                   short_desc text,
                                   retail_price bigint,
                                   tags text[],
                                   created_at timestamp with time zone NOT NULL,
                                   updated_at timestamp with time zone NOT NULL,
                                   note text,
                                   image_urls text[],
                                   status smallint,
                                   name_norm tsvector,
                                   product_id bigint,
                                   deleted_at timestamp with time zone,
                                   attr_norm_kv tsvector,
                                   code text,
                                   cost_price bigint,
                                   list_price bigint,
                                   attributes jsonb,
                                   external_id text,
                                   external_code text,
                                   partner_id bigint,
                                   code_norm bigint,
                                   external_product_id text
);

CREATE TABLE public.shop_variant_supplier (
                                            shop_id bigint,
                                            supplier_id bigint,
                                            variant_id bigint,
                                            created_at timestamp with time zone,
                                            updated_at timestamp with time zone,
                                            rid bigint NOT NULL
);

CREATE TABLE public.transaction (
                                  id bigint NOT NULL,
                                  amount bigint,
                                  account_id bigint,
                                  status smallint,
                                  type text,
                                  note text,
                                  metadata jsonb,
                                  created_at timestamp with time zone,
                                  updated_at timestamp with time zone,
                                  rid bigint NOT NULL
);

CREATE TABLE public."user" (
                             id bigint NOT NULL,
                             rid bigint NOT NULL,
                             status smallint NOT NULL,
                             created_at timestamp with time zone NOT NULL,
                             updated_at timestamp with time zone NOT NULL,
                             full_name text,
                             short_name text,
                             email text,
                             phone text,
                             agreed_tos_at timestamp with time zone,
                             agreed_email_info_at timestamp with time zone,
                             email_verified_at timestamp with time zone,
                             phone_verified_at timestamp with time zone,
                             email_verification_sent_at timestamp with time zone,
                             phone_verification_sent_at timestamp with time zone,
                             is_test smallint NOT NULL,
                             identifying public.user_identifying_type,
                             source text,
                             ref_user_id bigint,
                             ref_sale_id bigint,
                             wl_partner_id bigint,
                             CONSTRAINT user_identifying CHECK ((((identifying = 'full'::public.user_identifying_type) AND (status <> 0) AND (phone IS NOT NULL) AND (email IS NOT NULL)) OR ((identifying = 'half'::public.user_identifying_type) AND (status <> 0) AND (phone IS NOT NULL)) OR ((identifying = 'stub'::public.user_identifying_type) AND (status = 0) AND ((phone IS NOT NULL) OR (email IS NOT NULL))))),
                             CONSTRAINT user_not_full CHECK (((identifying = 'stub'::public.user_identifying_type) OR ((full_name IS NOT NULL) AND (short_name IS NOT NULL))))
);

CREATE TABLE public.user_auth (
                                user_id bigint,
                                auth_type text NOT NULL,
                                auth_key text NOT NULL,
                                created_at timestamp with time zone,
                                updated_at timestamp with time zone
);

CREATE TABLE public.user_internal (
                                    id bigint NOT NULL,
                                    hashpwd text,
                                    updated_at timestamp with time zone,
                                    rid bigint NOT NULL
);

CREATE TABLE public.webhook (
                              id bigint NOT NULL,
                              account_id bigint NOT NULL,
                              entities text[],
                              fields text[],
                              url text NOT NULL,
                              metadata text,
                              created_at timestamp with time zone,
                              updated_at timestamp with time zone,
                              deleted_at timestamp with time zone,
                              rid bigint NOT NULL
);

CREATE TABLE public.webhook_changes (
                                      id bigint NOT NULL,
                                      webhook_id bigint NOT NULL,
                                      account_id bigint NOT NULL,
                                      created_at timestamp with time zone,
                                      changes jsonb,
                                      result jsonb
);
