// +build !generator

// Code generated by generator event. DO NOT EDIT.

package etelecom

func (e *CallLogCalcPostageEvent) GetTopic() string { return "event/etelecom" }
func (e *ExtensionCreatingEvent) GetTopic() string  { return "event/etelecom" }
func (e *TenantActivingEvent) GetTopic() string     { return "event/etelecom" }
