// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: etop.vn/api/main/shipnow/v1/api.proto

package v1

import (
	fmt "fmt"
	math "math"

	types "etop.vn/api/main/ordering/v1/types"
	types1 "etop.vn/api/main/shipping/v1/types"
	v1 "etop.vn/api/meta/v1"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

func (m *ShipnowFulfillment) Reset()         { *m = ShipnowFulfillment{} }
func (m *ShipnowFulfillment) String() string { return proto.CompactTextString(m) }
func (*ShipnowFulfillment) ProtoMessage()    {}
func (*ShipnowFulfillment) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c324fa88396454, []int{0}
}
func (m *ShipnowFulfillment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipnowFulfillment.Unmarshal(m, b)
}
func (m *ShipnowFulfillment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipnowFulfillment.Marshal(b, m, deterministic)
}
func (m *ShipnowFulfillment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipnowFulfillment.Merge(m, src)
}
func (m *ShipnowFulfillment) XXX_Size() int {
	return xxx_messageInfo_ShipnowFulfillment.Size(m)
}
func (m *ShipnowFulfillment) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipnowFulfillment.DiscardUnknown(m)
}

var xxx_messageInfo_ShipnowFulfillment proto.InternalMessageInfo

func (m *ShipnowFulfillment) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ShipnowFulfillment) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *ShipnowFulfillment) GetPartnerId() int64 {
	if m != nil {
		return m.PartnerId
	}
	return 0
}

func (m *ShipnowFulfillment) GetPickupAddress() *types.Address {
	if m != nil {
		return m.PickupAddress
	}
	return nil
}

func (m *ShipnowFulfillment) GetDeliveryPoints() []*DeliveryPoint {
	if m != nil {
		return m.DeliveryPoints
	}
	return nil
}

func (m *ShipnowFulfillment) GetCarrier() string {
	if m != nil {
		return m.Carrier
	}
	return ""
}

func (m *ShipnowFulfillment) GetShippingServiceCode() string {
	if m != nil {
		return m.ShippingServiceCode
	}
	return ""
}

func (m *ShipnowFulfillment) GetShippingServiceFee() int32 {
	if m != nil {
		return m.ShippingServiceFee
	}
	return 0
}

func (m *ShipnowFulfillment) GetValueInfo() types1.ValueInfo {
	if m != nil {
		return m.ValueInfo
	}
	return types1.ValueInfo{}
}

func (m *ShipnowFulfillment) GetShippingNote() string {
	if m != nil {
		return m.ShippingNote
	}
	return ""
}

func (m *ShipnowFulfillment) GetRequestPickupAt() *v1.Timestamp {
	if m != nil {
		return m.RequestPickupAt
	}
	return nil
}

func (m *DeliveryPoint) Reset()         { *m = DeliveryPoint{} }
func (m *DeliveryPoint) String() string { return proto.CompactTextString(m) }
func (*DeliveryPoint) ProtoMessage()    {}
func (*DeliveryPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c324fa88396454, []int{1}
}
func (m *DeliveryPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliveryPoint.Unmarshal(m, b)
}
func (m *DeliveryPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliveryPoint.Marshal(b, m, deterministic)
}
func (m *DeliveryPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliveryPoint.Merge(m, src)
}
func (m *DeliveryPoint) XXX_Size() int {
	return xxx_messageInfo_DeliveryPoint.Size(m)
}
func (m *DeliveryPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliveryPoint.DiscardUnknown(m)
}

var xxx_messageInfo_DeliveryPoint proto.InternalMessageInfo

func (m *DeliveryPoint) GetShippingAddress() *types.Address {
	if m != nil {
		return m.ShippingAddress
	}
	return nil
}

func (m *DeliveryPoint) GetLines() []*types.ItemLine {
	if m != nil {
		return m.Lines
	}
	return nil
}

func (m *DeliveryPoint) GetShippingNote() string {
	if m != nil {
		return m.ShippingNote
	}
	return ""
}

func (m *DeliveryPoint) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *DeliveryPoint) GetTryOn() types1.TryOnCode {
	if m != nil {
		return m.TryOn
	}
	return types1.TryOnCode_unknown
}

func (m *CreateShipnowFulfillmentCommand) Reset()         { *m = CreateShipnowFulfillmentCommand{} }
func (m *CreateShipnowFulfillmentCommand) String() string { return proto.CompactTextString(m) }
func (*CreateShipnowFulfillmentCommand) ProtoMessage()    {}
func (*CreateShipnowFulfillmentCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c324fa88396454, []int{2}
}
func (m *CreateShipnowFulfillmentCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShipnowFulfillmentCommand.Unmarshal(m, b)
}
func (m *CreateShipnowFulfillmentCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShipnowFulfillmentCommand.Marshal(b, m, deterministic)
}
func (m *CreateShipnowFulfillmentCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShipnowFulfillmentCommand.Merge(m, src)
}
func (m *CreateShipnowFulfillmentCommand) XXX_Size() int {
	return xxx_messageInfo_CreateShipnowFulfillmentCommand.Size(m)
}
func (m *CreateShipnowFulfillmentCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShipnowFulfillmentCommand.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShipnowFulfillmentCommand proto.InternalMessageInfo

func (m *ConfirmShipnowFulfillmentCommand) Reset()         { *m = ConfirmShipnowFulfillmentCommand{} }
func (m *ConfirmShipnowFulfillmentCommand) String() string { return proto.CompactTextString(m) }
func (*ConfirmShipnowFulfillmentCommand) ProtoMessage()    {}
func (*ConfirmShipnowFulfillmentCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c324fa88396454, []int{3}
}
func (m *ConfirmShipnowFulfillmentCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmShipnowFulfillmentCommand.Unmarshal(m, b)
}
func (m *ConfirmShipnowFulfillmentCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmShipnowFulfillmentCommand.Marshal(b, m, deterministic)
}
func (m *ConfirmShipnowFulfillmentCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmShipnowFulfillmentCommand.Merge(m, src)
}
func (m *ConfirmShipnowFulfillmentCommand) XXX_Size() int {
	return xxx_messageInfo_ConfirmShipnowFulfillmentCommand.Size(m)
}
func (m *ConfirmShipnowFulfillmentCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmShipnowFulfillmentCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmShipnowFulfillmentCommand proto.InternalMessageInfo

func (m *ConfirmShipnowFulfillmentCommand) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CancelShipnowFulfillmentCommand) Reset()         { *m = CancelShipnowFulfillmentCommand{} }
func (m *CancelShipnowFulfillmentCommand) String() string { return proto.CompactTextString(m) }
func (*CancelShipnowFulfillmentCommand) ProtoMessage()    {}
func (*CancelShipnowFulfillmentCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c324fa88396454, []int{4}
}
func (m *CancelShipnowFulfillmentCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelShipnowFulfillmentCommand.Unmarshal(m, b)
}
func (m *CancelShipnowFulfillmentCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelShipnowFulfillmentCommand.Marshal(b, m, deterministic)
}
func (m *CancelShipnowFulfillmentCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelShipnowFulfillmentCommand.Merge(m, src)
}
func (m *CancelShipnowFulfillmentCommand) XXX_Size() int {
	return xxx_messageInfo_CancelShipnowFulfillmentCommand.Size(m)
}
func (m *CancelShipnowFulfillmentCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelShipnowFulfillmentCommand.DiscardUnknown(m)
}

var xxx_messageInfo_CancelShipnowFulfillmentCommand proto.InternalMessageInfo

func (m *CancelShipnowFulfillmentCommand) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CancelShipnowFulfillmentCommand) GetCancelReason() string {
	if m != nil {
		return m.CancelReason
	}
	return ""
}

func (m *GetShipnowFulfillmentQueryArgs) Reset()         { *m = GetShipnowFulfillmentQueryArgs{} }
func (m *GetShipnowFulfillmentQueryArgs) String() string { return proto.CompactTextString(m) }
func (*GetShipnowFulfillmentQueryArgs) ProtoMessage()    {}
func (*GetShipnowFulfillmentQueryArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c324fa88396454, []int{5}
}
func (m *GetShipnowFulfillmentQueryArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShipnowFulfillmentQueryArgs.Unmarshal(m, b)
}
func (m *GetShipnowFulfillmentQueryArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShipnowFulfillmentQueryArgs.Marshal(b, m, deterministic)
}
func (m *GetShipnowFulfillmentQueryArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShipnowFulfillmentQueryArgs.Merge(m, src)
}
func (m *GetShipnowFulfillmentQueryArgs) XXX_Size() int {
	return xxx_messageInfo_GetShipnowFulfillmentQueryArgs.Size(m)
}
func (m *GetShipnowFulfillmentQueryArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShipnowFulfillmentQueryArgs.DiscardUnknown(m)
}

var xxx_messageInfo_GetShipnowFulfillmentQueryArgs proto.InternalMessageInfo

func (m *GetShipnowFulfillmentQueryArgs) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetShipnowFulfillmentQueryResult) Reset()         { *m = GetShipnowFulfillmentQueryResult{} }
func (m *GetShipnowFulfillmentQueryResult) String() string { return proto.CompactTextString(m) }
func (*GetShipnowFulfillmentQueryResult) ProtoMessage()    {}
func (*GetShipnowFulfillmentQueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c324fa88396454, []int{6}
}
func (m *GetShipnowFulfillmentQueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShipnowFulfillmentQueryResult.Unmarshal(m, b)
}
func (m *GetShipnowFulfillmentQueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShipnowFulfillmentQueryResult.Marshal(b, m, deterministic)
}
func (m *GetShipnowFulfillmentQueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShipnowFulfillmentQueryResult.Merge(m, src)
}
func (m *GetShipnowFulfillmentQueryResult) XXX_Size() int {
	return xxx_messageInfo_GetShipnowFulfillmentQueryResult.Size(m)
}
func (m *GetShipnowFulfillmentQueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShipnowFulfillmentQueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetShipnowFulfillmentQueryResult proto.InternalMessageInfo

func (m *ShipnowEvent) Reset()         { *m = ShipnowEvent{} }
func (m *ShipnowEvent) String() string { return proto.CompactTextString(m) }
func (*ShipnowEvent) ProtoMessage()    {}
func (*ShipnowEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c324fa88396454, []int{7}
}
func (m *ShipnowEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipnowEvent.Unmarshal(m, b)
}
func (m *ShipnowEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipnowEvent.Marshal(b, m, deterministic)
}
func (m *ShipnowEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipnowEvent.Merge(m, src)
}
func (m *ShipnowEvent) XXX_Size() int {
	return xxx_messageInfo_ShipnowEvent.Size(m)
}
func (m *ShipnowEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipnowEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ShipnowEvent proto.InternalMessageInfo

func (m *ShipnowEvent) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ShipnowEvent) GetUuid() v1.UUID {
	if m != nil {
		return m.Uuid
	}
	return v1.UUID{}
}

func (m *ShipnowEvent) GetCorrelationId() v1.UUID {
	if m != nil {
		return m.CorrelationId
	}
	return v1.UUID{}
}

func (m *ShipnowEvent) GetShipnowFulfillmentId() int64 {
	if m != nil {
		return m.ShipnowFulfillmentId
	}
	return 0
}

func (m *ShipnowEvent) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ShipnowEvent) GetData() *EventData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *EventData) Reset()         { *m = EventData{} }
func (m *EventData) String() string { return proto.CompactTextString(m) }
func (*EventData) ProtoMessage()    {}
func (*EventData) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c324fa88396454, []int{8}
}
func (m *EventData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventData.Unmarshal(m, b)
}
func (m *EventData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventData.Marshal(b, m, deterministic)
}
func (m *EventData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventData.Merge(m, src)
}
func (m *EventData) XXX_Size() int {
	return xxx_messageInfo_EventData.Size(m)
}
func (m *EventData) XXX_DiscardUnknown() {
	xxx_messageInfo_EventData.DiscardUnknown(m)
}

var xxx_messageInfo_EventData proto.InternalMessageInfo

func (*EventData_Created) isEventData_Data()               {}
func (*EventData_ConfirmationRequested) isEventData_Data() {}
func (*EventData_ConfirmationAccepted) isEventData_Data()  {}
func (*EventData_ConfirmationRejected) isEventData_Data()  {}
func (*EventData_CancellationRequested) isEventData_Data() {}
func (*EventData_CancellationAccepted) isEventData_Data()  {}
func (*EventData_CancellationRejected) isEventData_Data()  {}

func (m *EventData) GetData() isEventData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *EventData) GetCreated() *CreatedData {
	if x, ok := m.GetData().(*EventData_Created); ok {
		return x.Created
	}
	return nil
}

func (m *EventData) GetConfirmationRequested() *ConfirmationRequestedData {
	if x, ok := m.GetData().(*EventData_ConfirmationRequested); ok {
		return x.ConfirmationRequested
	}
	return nil
}

func (m *EventData) GetConfirmationAccepted() *ConfirmationAcceptedData {
	if x, ok := m.GetData().(*EventData_ConfirmationAccepted); ok {
		return x.ConfirmationAccepted
	}
	return nil
}

func (m *EventData) GetConfirmationRejected() *ConfirmationRejectedData {
	if x, ok := m.GetData().(*EventData_ConfirmationRejected); ok {
		return x.ConfirmationRejected
	}
	return nil
}

func (m *EventData) GetCancellationRequested() *CancellationRequestedData {
	if x, ok := m.GetData().(*EventData_CancellationRequested); ok {
		return x.CancellationRequested
	}
	return nil
}

func (m *EventData) GetCancellationAccepted() *CancellationAcceptedData {
	if x, ok := m.GetData().(*EventData_CancellationAccepted); ok {
		return x.CancellationAccepted
	}
	return nil
}

func (m *EventData) GetCancellationRejected() *CancellationRejectedData {
	if x, ok := m.GetData().(*EventData_CancellationRejected); ok {
		return x.CancellationRejected
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*EventData) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _EventData_OneofMarshaler, _EventData_OneofUnmarshaler, _EventData_OneofSizer, []interface{}{
		(*EventData_Created)(nil),
		(*EventData_ConfirmationRequested)(nil),
		(*EventData_ConfirmationAccepted)(nil),
		(*EventData_ConfirmationRejected)(nil),
		(*EventData_CancellationRequested)(nil),
		(*EventData_CancellationAccepted)(nil),
		(*EventData_CancellationRejected)(nil),
	}
}

func _EventData_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*EventData)
	// data
	switch x := m.Data.(type) {
	case *EventData_Created:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Created); err != nil {
			return err
		}
	case *EventData_ConfirmationRequested:
		_ = b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ConfirmationRequested); err != nil {
			return err
		}
	case *EventData_ConfirmationAccepted:
		_ = b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ConfirmationAccepted); err != nil {
			return err
		}
	case *EventData_ConfirmationRejected:
		_ = b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ConfirmationRejected); err != nil {
			return err
		}
	case *EventData_CancellationRequested:
		_ = b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CancellationRequested); err != nil {
			return err
		}
	case *EventData_CancellationAccepted:
		_ = b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CancellationAccepted); err != nil {
			return err
		}
	case *EventData_CancellationRejected:
		_ = b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CancellationRejected); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("EventData.Data has unexpected type %T", x)
	}
	return nil
}

func _EventData_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*EventData)
	switch tag {
	case 1: // data.Created
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreatedData)
		err := b.DecodeMessage(msg)
		m.Data = &EventData_Created{msg}
		return true, err
	case 4: // data.ConfirmationRequested
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ConfirmationRequestedData)
		err := b.DecodeMessage(msg)
		m.Data = &EventData_ConfirmationRequested{msg}
		return true, err
	case 5: // data.ConfirmationAccepted
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ConfirmationAcceptedData)
		err := b.DecodeMessage(msg)
		m.Data = &EventData_ConfirmationAccepted{msg}
		return true, err
	case 6: // data.ConfirmationRejected
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ConfirmationRejectedData)
		err := b.DecodeMessage(msg)
		m.Data = &EventData_ConfirmationRejected{msg}
		return true, err
	case 7: // data.CancellationRequested
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CancellationRequestedData)
		err := b.DecodeMessage(msg)
		m.Data = &EventData_CancellationRequested{msg}
		return true, err
	case 8: // data.CancellationAccepted
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CancellationAcceptedData)
		err := b.DecodeMessage(msg)
		m.Data = &EventData_CancellationAccepted{msg}
		return true, err
	case 9: // data.CancellationRejected
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CancellationRejectedData)
		err := b.DecodeMessage(msg)
		m.Data = &EventData_CancellationRejected{msg}
		return true, err
	default:
		return false, nil
	}
}

func _EventData_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*EventData)
	// data
	switch x := m.Data.(type) {
	case *EventData_Created:
		s := proto.Size(x.Created)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EventData_ConfirmationRequested:
		s := proto.Size(x.ConfirmationRequested)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EventData_ConfirmationAccepted:
		s := proto.Size(x.ConfirmationAccepted)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EventData_ConfirmationRejected:
		s := proto.Size(x.ConfirmationRejected)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EventData_CancellationRequested:
		s := proto.Size(x.CancellationRequested)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EventData_CancellationAccepted:
		s := proto.Size(x.CancellationAccepted)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EventData_CancellationRejected:
		s := proto.Size(x.CancellationRejected)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func (m *CreatedData) Reset()         { *m = CreatedData{} }
func (m *CreatedData) String() string { return proto.CompactTextString(m) }
func (*CreatedData) ProtoMessage()    {}
func (*CreatedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c324fa88396454, []int{9}
}
func (m *CreatedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatedData.Unmarshal(m, b)
}
func (m *CreatedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatedData.Marshal(b, m, deterministic)
}
func (m *CreatedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatedData.Merge(m, src)
}
func (m *CreatedData) XXX_Size() int {
	return xxx_messageInfo_CreatedData.Size(m)
}
func (m *CreatedData) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatedData.DiscardUnknown(m)
}

var xxx_messageInfo_CreatedData proto.InternalMessageInfo

func (m *ConfirmationRequestedData) Reset()         { *m = ConfirmationRequestedData{} }
func (m *ConfirmationRequestedData) String() string { return proto.CompactTextString(m) }
func (*ConfirmationRequestedData) ProtoMessage()    {}
func (*ConfirmationRequestedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c324fa88396454, []int{10}
}
func (m *ConfirmationRequestedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmationRequestedData.Unmarshal(m, b)
}
func (m *ConfirmationRequestedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmationRequestedData.Marshal(b, m, deterministic)
}
func (m *ConfirmationRequestedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmationRequestedData.Merge(m, src)
}
func (m *ConfirmationRequestedData) XXX_Size() int {
	return xxx_messageInfo_ConfirmationRequestedData.Size(m)
}
func (m *ConfirmationRequestedData) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmationRequestedData.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmationRequestedData proto.InternalMessageInfo

func (m *ConfirmationAcceptedData) Reset()         { *m = ConfirmationAcceptedData{} }
func (m *ConfirmationAcceptedData) String() string { return proto.CompactTextString(m) }
func (*ConfirmationAcceptedData) ProtoMessage()    {}
func (*ConfirmationAcceptedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c324fa88396454, []int{11}
}
func (m *ConfirmationAcceptedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmationAcceptedData.Unmarshal(m, b)
}
func (m *ConfirmationAcceptedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmationAcceptedData.Marshal(b, m, deterministic)
}
func (m *ConfirmationAcceptedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmationAcceptedData.Merge(m, src)
}
func (m *ConfirmationAcceptedData) XXX_Size() int {
	return xxx_messageInfo_ConfirmationAcceptedData.Size(m)
}
func (m *ConfirmationAcceptedData) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmationAcceptedData.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmationAcceptedData proto.InternalMessageInfo

func (m *ConfirmationRejectedData) Reset()         { *m = ConfirmationRejectedData{} }
func (m *ConfirmationRejectedData) String() string { return proto.CompactTextString(m) }
func (*ConfirmationRejectedData) ProtoMessage()    {}
func (*ConfirmationRejectedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c324fa88396454, []int{12}
}
func (m *ConfirmationRejectedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmationRejectedData.Unmarshal(m, b)
}
func (m *ConfirmationRejectedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmationRejectedData.Marshal(b, m, deterministic)
}
func (m *ConfirmationRejectedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmationRejectedData.Merge(m, src)
}
func (m *ConfirmationRejectedData) XXX_Size() int {
	return xxx_messageInfo_ConfirmationRejectedData.Size(m)
}
func (m *ConfirmationRejectedData) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmationRejectedData.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmationRejectedData proto.InternalMessageInfo

func (m *CancellationRequestedData) Reset()         { *m = CancellationRequestedData{} }
func (m *CancellationRequestedData) String() string { return proto.CompactTextString(m) }
func (*CancellationRequestedData) ProtoMessage()    {}
func (*CancellationRequestedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c324fa88396454, []int{13}
}
func (m *CancellationRequestedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancellationRequestedData.Unmarshal(m, b)
}
func (m *CancellationRequestedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancellationRequestedData.Marshal(b, m, deterministic)
}
func (m *CancellationRequestedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancellationRequestedData.Merge(m, src)
}
func (m *CancellationRequestedData) XXX_Size() int {
	return xxx_messageInfo_CancellationRequestedData.Size(m)
}
func (m *CancellationRequestedData) XXX_DiscardUnknown() {
	xxx_messageInfo_CancellationRequestedData.DiscardUnknown(m)
}

var xxx_messageInfo_CancellationRequestedData proto.InternalMessageInfo

func (m *CancellationAcceptedData) Reset()         { *m = CancellationAcceptedData{} }
func (m *CancellationAcceptedData) String() string { return proto.CompactTextString(m) }
func (*CancellationAcceptedData) ProtoMessage()    {}
func (*CancellationAcceptedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c324fa88396454, []int{14}
}
func (m *CancellationAcceptedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancellationAcceptedData.Unmarshal(m, b)
}
func (m *CancellationAcceptedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancellationAcceptedData.Marshal(b, m, deterministic)
}
func (m *CancellationAcceptedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancellationAcceptedData.Merge(m, src)
}
func (m *CancellationAcceptedData) XXX_Size() int {
	return xxx_messageInfo_CancellationAcceptedData.Size(m)
}
func (m *CancellationAcceptedData) XXX_DiscardUnknown() {
	xxx_messageInfo_CancellationAcceptedData.DiscardUnknown(m)
}

var xxx_messageInfo_CancellationAcceptedData proto.InternalMessageInfo

func (m *CancellationRejectedData) Reset()         { *m = CancellationRejectedData{} }
func (m *CancellationRejectedData) String() string { return proto.CompactTextString(m) }
func (*CancellationRejectedData) ProtoMessage()    {}
func (*CancellationRejectedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c324fa88396454, []int{15}
}
func (m *CancellationRejectedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancellationRejectedData.Unmarshal(m, b)
}
func (m *CancellationRejectedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancellationRejectedData.Marshal(b, m, deterministic)
}
func (m *CancellationRejectedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancellationRejectedData.Merge(m, src)
}
func (m *CancellationRejectedData) XXX_Size() int {
	return xxx_messageInfo_CancellationRejectedData.Size(m)
}
func (m *CancellationRejectedData) XXX_DiscardUnknown() {
	xxx_messageInfo_CancellationRejectedData.DiscardUnknown(m)
}

var xxx_messageInfo_CancellationRejectedData proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ShipnowFulfillment)(nil), "etop.vn.api.main.shipnow.v1.ShipnowFulfillment")
	proto.RegisterType((*DeliveryPoint)(nil), "etop.vn.api.main.shipnow.v1.DeliveryPoint")
	proto.RegisterType((*CreateShipnowFulfillmentCommand)(nil), "etop.vn.api.main.shipnow.v1.CreateShipnowFulfillmentCommand")
	proto.RegisterType((*ConfirmShipnowFulfillmentCommand)(nil), "etop.vn.api.main.shipnow.v1.ConfirmShipnowFulfillmentCommand")
	proto.RegisterType((*CancelShipnowFulfillmentCommand)(nil), "etop.vn.api.main.shipnow.v1.CancelShipnowFulfillmentCommand")
	proto.RegisterType((*GetShipnowFulfillmentQueryArgs)(nil), "etop.vn.api.main.shipnow.v1.GetShipnowFulfillmentQueryArgs")
	proto.RegisterType((*GetShipnowFulfillmentQueryResult)(nil), "etop.vn.api.main.shipnow.v1.GetShipnowFulfillmentQueryResult")
	proto.RegisterType((*ShipnowEvent)(nil), "etop.vn.api.main.shipnow.v1.ShipnowEvent")
	proto.RegisterType((*EventData)(nil), "etop.vn.api.main.shipnow.v1.EventData")
	proto.RegisterType((*CreatedData)(nil), "etop.vn.api.main.shipnow.v1.CreatedData")
	proto.RegisterType((*ConfirmationRequestedData)(nil), "etop.vn.api.main.shipnow.v1.ConfirmationRequestedData")
	proto.RegisterType((*ConfirmationAcceptedData)(nil), "etop.vn.api.main.shipnow.v1.ConfirmationAcceptedData")
	proto.RegisterType((*ConfirmationRejectedData)(nil), "etop.vn.api.main.shipnow.v1.ConfirmationRejectedData")
	proto.RegisterType((*CancellationRequestedData)(nil), "etop.vn.api.main.shipnow.v1.CancellationRequestedData")
	proto.RegisterType((*CancellationAcceptedData)(nil), "etop.vn.api.main.shipnow.v1.CancellationAcceptedData")
	proto.RegisterType((*CancellationRejectedData)(nil), "etop.vn.api.main.shipnow.v1.CancellationRejectedData")
}

func init() {
	proto.RegisterFile("etop.vn/api/main/shipnow/v1/api.proto", fileDescriptor_76c324fa88396454)
}

var fileDescriptor_76c324fa88396454 = []byte{
	// 1148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0xde, 0xf5, 0xcf, 0xe4, 0xb9, 0x49, 0x61, 0x9a, 0xa2, 0xad, 0xab, 0x6e, 0xac, 0x45, 0x20,
	0xf3, 0x6b, 0xad, 0x04, 0x11, 0x55, 0xa5, 0x3d, 0xe4, 0x47, 0x03, 0xae, 0x28, 0x94, 0x4d, 0x1b,
	0x04, 0x17, 0x6b, 0xf1, 0x8e, 0x9d, 0xa5, 0xf6, 0xcc, 0x32, 0x3b, 0xde, 0xc8, 0xff, 0x01, 0x70,
	0x42, 0xe2, 0xc2, 0x9f, 0x80, 0xc4, 0x91, 0x0b, 0x7f, 0x42, 0x6e, 0xe4, 0xc8, 0xa9, 0x6a, 0x9c,
	0x33, 0x12, 0x27, 0xce, 0x68, 0x67, 0x67, 0xdd, 0xb5, 0xbd, 0x6b, 0xec, 0x8a, 0x4b, 0x55, 0xcf,
	0x7b, 0xdf, 0xf7, 0xe6, 0x7d, 0xfb, 0xcd, 0x7b, 0x81, 0x37, 0x30, 0xa7, 0x9e, 0x19, 0x90, 0x86,
	0xed, 0xb9, 0x8d, 0xbe, 0xed, 0x92, 0x86, 0x7f, 0xe2, 0x7a, 0x84, 0x9e, 0x36, 0x82, 0xad, 0xf0,
	0xcc, 0xf4, 0x18, 0xe5, 0x14, 0xdd, 0x94, 0x69, 0x66, 0x78, 0x14, 0xa6, 0x99, 0x32, 0xcd, 0x0c,
	0xb6, 0xaa, 0x1b, 0x5d, 0xda, 0xa5, 0x22, 0xaf, 0x11, 0xfe, 0x2f, 0x82, 0x54, 0xcd, 0x19, 0x66,
	0xca, 0x1c, 0xcc, 0x5c, 0xd2, 0x0d, 0xa9, 0xf9, 0xd0, 0xc3, 0x7e, 0xf4, 0x6f, 0x66, 0x7e, 0x58,
	0xc2, 0x9b, 0xcc, 0x67, 0x43, 0x4a, 0x96, 0xc9, 0x4f, 0xf0, 0xdf, 0x9a, 0xc8, 0xc7, 0xdc, 0x9e,
	0xe8, 0xd0, 0xf8, 0xa3, 0x08, 0xe8, 0x28, 0xea, 0xe9, 0x70, 0xd0, 0xeb, 0xb8, 0xbd, 0x5e, 0x1f,
	0x13, 0x8e, 0x36, 0x20, 0xe7, 0x3a, 0x9a, 0x5a, 0x53, 0xeb, 0xf9, 0xbd, 0xc2, 0xd9, 0xb3, 0x4d,
	0xc5, 0xca, 0xb9, 0x0e, 0xba, 0x05, 0x65, 0xff, 0x84, 0x7a, 0x2d, 0xd7, 0xd1, 0x72, 0x89, 0x50,
	0x29, 0x3c, 0x6c, 0x3a, 0xe8, 0x75, 0x00, 0xcf, 0x66, 0x9c, 0x60, 0x16, 0x66, 0xe4, 0x13, 0x19,
	0xab, 0xf2, 0xbc, 0xe9, 0x20, 0x0b, 0xd6, 0x3d, 0xb7, 0xfd, 0x74, 0xe0, 0xb5, 0x6c, 0xc7, 0x61,
	0xd8, 0xf7, 0xb5, 0x42, 0x4d, 0xad, 0x57, 0xb6, 0xdf, 0x31, 0x67, 0xb4, 0x8e, 0x85, 0x33, 0x83,
	0x2d, 0x33, 0x6a, 0x69, 0x37, 0x82, 0x58, 0x6b, 0x11, 0x85, 0xfc, 0x89, 0x8e, 0xe0, 0xaa, 0x83,
	0x7b, 0x6e, 0x80, 0xd9, 0xb0, 0xe5, 0x51, 0x97, 0x70, 0x5f, 0x2b, 0xd6, 0xf2, 0xf5, 0xca, 0xf6,
	0xdb, 0xe6, 0x9c, 0x0f, 0x68, 0x1e, 0x48, 0xcc, 0xa3, 0x10, 0x62, 0xad, 0x3b, 0xc9, 0x9f, 0x3e,
	0xd2, 0xa1, 0xdc, 0xb6, 0x19, 0x73, 0x31, 0xd3, 0x4a, 0x35, 0xb5, 0xbe, 0x2a, 0x5b, 0x89, 0x0f,
	0xd1, 0x6d, 0xb8, 0x1e, 0x2b, 0xdf, 0xf2, 0x31, 0x0b, 0xdc, 0x36, 0x6e, 0xb5, 0xa9, 0x83, 0xb5,
	0x72, 0x22, 0xfb, 0x5a, 0x9c, 0x72, 0x14, 0x65, 0xec, 0x53, 0x07, 0xa3, 0x1d, 0xd8, 0x98, 0x41,
	0x76, 0x30, 0xd6, 0x56, 0x6a, 0x6a, 0xbd, 0x28, 0x81, 0x68, 0x0a, 0x78, 0x88, 0x31, 0xfa, 0x12,
	0x2a, 0xa7, 0xd8, 0xed, 0x9e, 0xf0, 0x96, 0x4b, 0x3a, 0x54, 0x5b, 0x15, 0xba, 0x99, 0xe9, 0x2d,
	0x7a, 0x13, 0xba, 0x7d, 0x21, 0x60, 0x4d, 0xd2, 0xa1, 0x7b, 0x2b, 0x21, 0xfd, 0xf9, 0xb3, 0x4d,
	0xd5, 0x82, 0xd3, 0xf1, 0x29, 0xb2, 0x00, 0x02, 0xbb, 0x37, 0xc0, 0x11, 0x33, 0x08, 0xe6, 0xf7,
	0x16, 0x61, 0x3e, 0x0e, 0x51, 0x82, 0x58, 0x7e, 0xe9, 0x20, 0x3e, 0x40, 0x6f, 0xc1, 0xda, 0xb8,
	0x4d, 0x42, 0x39, 0xd6, 0x2a, 0x09, 0x61, 0xae, 0xc4, 0xa1, 0x4f, 0x29, 0xc7, 0xe8, 0x01, 0xbc,
	0xca, 0xf0, 0xb7, 0x03, 0xec, 0xf3, 0x56, 0x6c, 0x0e, 0xae, 0x5d, 0x11, 0xb7, 0xd0, 0x27, 0x6f,
	0x81, 0xb9, 0x1d, 0x16, 0x7f, 0xec, 0xf6, 0xb1, 0xcf, 0xed, 0xbe, 0x67, 0x5d, 0x95, 0xc0, 0x47,
	0x91, 0x23, 0xb8, 0xf1, 0x4f, 0x1e, 0xd6, 0x26, 0xbe, 0x2c, 0x3a, 0x86, 0x57, 0xc6, 0x17, 0x89,
	0x4d, 0xa7, 0x2e, 0x6f, 0xba, 0xab, 0x31, 0x49, 0x6c, 0xbb, 0x3d, 0x28, 0xf6, 0x5c, 0x82, 0x7d,
	0x2d, 0x27, 0xcc, 0xf6, 0xee, 0x22, 0x64, 0x4d, 0x8e, 0xfb, 0x9f, 0xb8, 0x04, 0x5b, 0x11, 0x74,
	0x56, 0xa4, 0x7c, 0xa6, 0x48, 0x9b, 0xb0, 0x22, 0xf8, 0xc2, 0xc7, 0x55, 0x48, 0x3c, 0xae, 0xb2,
	0x38, 0x6d, 0x3a, 0xd3, 0xfe, 0x28, 0xfe, 0x8f, 0xfe, 0x38, 0x9e, 0xf0, 0x47, 0xe9, 0x65, 0xfc,
	0xf1, 0x82, 0x38, 0xe1, 0x91, 0x07, 0x50, 0xe2, 0x6c, 0xd8, 0xa2, 0x44, 0x98, 0x63, 0xfd, 0x3f,
	0x39, 0xc5, 0x20, 0x7c, 0xcc, 0x86, 0x9f, 0x91, 0xf0, 0x25, 0x49, 0x01, 0x8a, 0x3c, 0x3c, 0x30,
	0x3c, 0xd8, 0xdc, 0x67, 0xd8, 0xe6, 0x78, 0x76, 0x9e, 0xed, 0xd3, 0x7e, 0xdf, 0x26, 0x0e, 0x7a,
	0x08, 0x05, 0xc7, 0xe6, 0xb6, 0xfc, 0xfa, 0x8d, 0xb9, 0xd3, 0x61, 0x96, 0x25, 0xd1, 0x82, 0xa0,
	0x31, 0x6e, 0x43, 0x6d, 0x9f, 0x92, 0x8e, 0xcb, 0xfa, 0xd9, 0x25, 0x53, 0x27, 0xa9, 0xf1, 0x35,
	0x6c, 0xee, 0xdb, 0xa4, 0x8d, 0x7b, 0x4b, 0x02, 0x43, 0xbf, 0xb4, 0x05, 0xb0, 0xc5, 0xb0, 0xed,
	0x53, 0x22, 0x06, 0xf1, 0xd8, 0x2f, 0x51, 0xc8, 0x12, 0x11, 0x63, 0x07, 0xf4, 0x8f, 0x30, 0x9f,
	0x2d, 0xf0, 0xf9, 0x00, 0xb3, 0xe1, 0x2e, 0xeb, 0xfa, 0x19, 0x77, 0x33, 0xa0, 0x96, 0x8d, 0xb3,
	0xb0, 0x3f, 0xe8, 0x71, 0xe3, 0xb7, 0x1c, 0x5c, 0x91, 0x19, 0xf7, 0x83, 0xec, 0x85, 0xf1, 0x3e,
	0x14, 0x06, 0x03, 0xb9, 0x2d, 0x2a, 0xdb, 0x37, 0x52, 0x9f, 0xf2, 0x93, 0x27, 0xcd, 0x03, 0x09,
	0x11, 0xc9, 0xe8, 0x10, 0xd6, 0xdb, 0x94, 0x31, 0xdc, 0xb3, 0xb9, 0x4b, 0x49, 0xbc, 0x4a, 0x16,
	0x80, 0xaf, 0x25, 0x60, 0x4d, 0x07, 0xdd, 0x81, 0xd7, 0xe4, 0xe7, 0x6c, 0x75, 0x5e, 0x74, 0x31,
	0xfd, 0x7a, 0x36, 0xfc, 0x99, 0x46, 0x9b, 0x0e, 0xd2, 0xa0, 0x10, 0xfa, 0x57, 0x4c, 0xc2, 0x78,
	0x24, 0x8b, 0x13, 0x74, 0x47, 0x5a, 0xa8, 0x22, 0xee, 0xf4, 0xe6, 0x5c, 0x0b, 0x09, 0x69, 0x0e,
	0x6c, 0x6e, 0x4b, 0xbf, 0xfc, 0x55, 0x84, 0xd5, 0xf1, 0x19, 0x3a, 0x80, 0x72, 0xe4, 0x57, 0x47,
	0xfa, 0xb1, 0x3e, 0x97, 0x4c, 0xe6, 0x86, 0xd0, 0x8f, 0x15, 0x2b, 0x86, 0x22, 0x02, 0xd7, 0xa5,
	0x07, 0x45, 0xdf, 0x56, 0x34, 0x0d, 0xb1, 0x23, 0xd7, 0xea, 0xce, 0x7c, 0xce, 0x34, 0xa4, 0xac,
	0x90, 0x4e, 0x8b, 0x9e, 0xc2, 0x46, 0x32, 0xb0, 0xdb, 0x6e, 0x63, 0x2f, 0x2c, 0x17, 0x4d, 0x9b,
	0x0f, 0x16, 0x2e, 0x17, 0x03, 0x65, 0xb5, 0x54, 0xd2, 0xe9, 0x62, 0x16, 0xfe, 0x06, 0xb7, 0xc3,
	0x62, 0xa5, 0x25, 0x8b, 0xc5, 0xc0, 0xb4, 0x62, 0x71, 0x4c, 0x28, 0x29, 0xde, 0x4f, 0x6f, 0x4a,
	0xc9, 0xf2, 0x22, 0x4a, 0xa6, 0x21, 0xc7, 0x4a, 0xa6, 0x05, 0x45, 0x73, 0x89, 0xc0, 0x58, 0xc9,
	0x95, 0x45, 0x9a, 0x4b, 0x01, 0x8e, 0x9b, 0x4b, 0x89, 0x4d, 0x17, 0x1b, 0x2b, 0xb9, 0xba, 0x64,
	0xb1, 0x19, 0x25, 0x53, 0x62, 0x7b, 0xa5, 0xe8, 0x8d, 0x18, 0x6b, 0x50, 0x49, 0xb8, 0xd6, 0xb8,
	0x09, 0x37, 0x32, 0x0d, 0x67, 0x54, 0x41, 0xcb, 0xb2, 0xc7, 0x74, 0x2c, 0x79, 0x07, 0x41, 0x9a,
	0xa5, 0xbd, 0x00, 0x66, 0x28, 0x35, 0x1d, 0x4b, 0x92, 0x6e, 0xff, 0x90, 0x87, 0x75, 0x39, 0xde,
	0x1e, 0xda, 0xc4, 0xee, 0x62, 0x86, 0xbe, 0x57, 0x41, 0xcb, 0x5a, 0x2f, 0xe8, 0xee, 0x02, 0x2f,
	0x37, 0x73, 0xd2, 0x57, 0x97, 0xdd, 0x43, 0x28, 0x18, 0x0b, 0x99, 0x12, 0xbc, 0xb7, 0xc8, 0xab,
	0xc8, 0xbe, 0x4c, 0x35, 0x75, 0xca, 0xde, 0xef, 0x7b, 0x7c, 0x88, 0x78, 0x2c, 0xd9, 0xf2, 0x12,
	0xcc, 0x5f, 0x76, 0xf3, 0xaa, 0x6e, 0xff, 0xaa, 0xc2, 0x35, 0x89, 0x14, 0x2b, 0x48, 0xfe, 0x45,
	0x8c, 0x7e, 0x52, 0xe1, 0x7a, 0xea, 0xa2, 0x42, 0x1f, 0xce, 0xbd, 0xcb, 0xfc, 0xa5, 0x58, 0xbd,
	0xf7, 0x92, 0xe0, 0x68, 0x33, 0xee, 0xdd, 0x3d, 0xbb, 0xd0, 0xd5, 0xf3, 0x0b, 0x5d, 0x79, 0x7e,
	0xa1, 0x2b, 0x7f, 0x5f, 0xe8, 0xca, 0x77, 0x23, 0x5d, 0xf9, 0x65, 0xa4, 0x2b, 0xbf, 0x8f, 0x74,
	0xe5, 0x6c, 0xa4, 0x2b, 0xe7, 0x23, 0x5d, 0x79, 0x3e, 0xd2, 0x95, 0x1f, 0x2f, 0x75, 0xe5, 0xe7,
	0x4b, 0x5d, 0x39, 0xbf, 0xd4, 0x95, 0x3f, 0x2f, 0x75, 0xe5, 0xab, 0x5c, 0xb0, 0xf5, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xf2, 0xd4, 0x21, 0x7f, 0x98, 0x0e, 0x00, 0x00,
}
