CREATE TABLE if not exists shop (
    id bigint PRIMARY KEY,
    rid bigint,
    name text,
    owner_id bigint,
    status int2,
    product_source_id int8,
    order_source_id int8,
    created_at timestamp with time zone DEFAULT date_trunc('second', now()),
    updated_at timestamp with time zone,
    rules jsonb,
    is_test smallint DEFAULT '0'::smallint,
    image_url text,
    phone text,
    website_url text,
    email text,
    deleted_at timestamp with time zone,
    address_id bigint,
    bank_account jsonb,
    contact_persons jsonb,
    inventory_overstock boolean,
    code text,
    auto_create_ffm boolean DEFAULT FALSE,
    recognized_hosts text[],
    ship_to_address_id int8,
    ship_from_address_id int8,
    ghn_note_code ghn_note_code,
    try_on try_on,
    company_info jsonb,
    money_transaction_rrule text,
    survey_info jsonb,
    shipping_service_select_strategy jsonb
);