CREATE TABLE if not exists shop_product (
    shop_id bigint,
    product_id bigint,
    rid bigint,
    collection_id bigint,
    name text,
    description text,
    desc_html text,
    short_desc text,
    retail_price integer,
    tags text[],
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    note text,
    image_urls text[],
    status smallint,
    brand_id int8,
    external_id text,
    external_code text,
    partner_id int8,
    external_brand_id text,
    external_category_id text,
    code text,
    unit text,
    category_id int8,
    cost_price integer,
    list_price integer,
    product_type text,
    meta_fields jsonb,
    PRIMARY KEY (shop_id, product_id)
);