new_database:
  protocol: ""
  host: postgres
  port: 5432
  username: postgres
  password: postgres
  database: etopv1.12
  sslmode: ""
  timeout: 15
  max_open_conns: 0
  max_idle_conns: 0
  max_conn_lifetime: 0
  google_auth_file: ""
old_database:
  protocol: ""
  host: postgres
  port: 5432
  username: postgres
  password: postgres
  database: test
  sslmode: ""
  timeout: 15
  max_open_conns: 0
  max_idle_conns: 0
  max_conn_lifetime: 0
  google_auth_file: ""

