rules:
- selectorRegexp: "o[.]o"
  allowedPrefixes:
  - o.o/api
  - o.o/backend/com
  - o.o/backend/pb
  - o.o/backend/pkg
  - o.o/backend/res/dl
  - o.o/capi
  - o.o/common
  - o.o/backend/zexp/api
  - o.o/backend/tools/pkg/acl # TODO: remove this
